// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CustomEquipment.Database.Migrations;

[DbContext(typeof(CustomEquipmentDbContext))]
internal sealed class CustomEquipmentDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("custom_equipment")
            .HasAnnotation("ProductVersion", "9.0.3")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("CustomEquipment.Database.Entities.EquipmentShopCategoryEntity", b =>
        {
            b.Property<long>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("bigint")
                .HasColumnName("id");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

            b.Property<DateTime>("CreatedAtUtc")
                .ValueGeneratedOnAdd()
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at")
                .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.Property<string>("Description")
                .IsRequired()
                .HasMaxLength(512)
                .HasColumnType("character varying(512)")
                .HasColumnName("description");

            b.Property<string>("DisplayName")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("character varying(128)")
                .HasColumnName("display_name");

            b.Property<bool>("Enabled")
                .ValueGeneratedOnAdd()
                .HasColumnType("boolean")
                .HasColumnName("enabled")
                .HasDefaultValue(true);

            b.Property<string>("Key")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("character varying(64)")
                .HasColumnName("key");

            b.Property<string>("ShopType")
                .IsRequired()
                .HasMaxLength(16)
                .HasColumnType("character varying(16)")
                .HasColumnName("shop_type");

            b.Property<int>("SortOrder")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer")
                .HasColumnName("sort_order")
                .HasDefaultValue(0);

            b.Property<DateTime>("UpdatedAtUtc")
                .ValueGeneratedOnAdd()
                .HasColumnType("timestamp with time zone")
                .HasColumnName("updated_at")
                .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.HasKey("Id");
            b.HasIndex("ShopType", "Enabled", "SortOrder");
            b.HasIndex("ShopType", "Key").IsUnique();

            b.ToTable("shop_categories", "custom_equipment", t =>
            {
                t.HasCheckConstraint("CK_shop_categories_type", "shop_type IN ('human', 'zombie')");
            });
        });

        modelBuilder.Entity("CustomEquipment.Database.Entities.EquipmentShopListingEntity", b =>
        {
            b.Property<long>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("bigint")
                .HasColumnName("id");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

            b.Property<long>("CategoryId")
                .HasColumnType("bigint")
                .HasColumnName("category_id");

            b.Property<DateTime>("CreatedAtUtc")
                .ValueGeneratedOnAdd()
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at")
                .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.Property<string>("Description")
                .IsRequired()
                .ValueGeneratedOnAdd()
                .HasMaxLength(1024)
                .HasColumnType("character varying(1024)")
                .HasColumnName("description")
                .HasDefaultValue("");

            b.Property<bool>("Enabled")
                .ValueGeneratedOnAdd()
                .HasColumnType("boolean")
                .HasColumnName("enabled")
                .HasDefaultValue(true);

            b.Property<string>("ItemInternalName")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("character varying(128)")
                .HasColumnName("item_internal_name");

            b.Property<int>("MaxPurchasesPerMap")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer")
                .HasColumnName("max_purchases_per_map")
                .HasDefaultValue(0);

            b.Property<int>("MaxPurchasesPerRound")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer")
                .HasColumnName("max_purchases_per_round")
                .HasDefaultValue(0);

            b.Property<int>("Price")
                .HasColumnType("integer")
                .HasColumnName("price");

            b.Property<string>("SettingsJson")
                .IsRequired()
                .ValueGeneratedOnAdd()
                .HasColumnType("jsonb")
                .HasColumnName("settings")
                .HasDefaultValueSql("'{}'::jsonb");

            b.Property<string>("ShopType")
                .IsRequired()
                .HasMaxLength(16)
                .HasColumnType("character varying(16)")
                .HasColumnName("shop_type");

            b.Property<int>("SortOrder")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer")
                .HasColumnName("sort_order")
                .HasDefaultValue(0);

            b.Property<DateTime>("UpdatedAtUtc")
                .ValueGeneratedOnAdd()
                .HasColumnType("timestamp with time zone")
                .HasColumnName("updated_at")
                .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.HasKey("Id");
            b.HasIndex("CategoryId");
            b.HasIndex("ShopType", "Enabled", "SortOrder");
            b.HasIndex("ShopType", "ItemInternalName").IsUnique();

            b.ToTable("shop_listings", "custom_equipment", t =>
            {
                t.HasCheckConstraint("CK_shop_listings_limits", "price >= 0 AND max_purchases_per_round >= 0 AND max_purchases_per_map >= 0");
                t.HasCheckConstraint("CK_shop_listings_settings_object", "jsonb_typeof(settings) = 'object'");
                t.HasCheckConstraint("CK_shop_listings_type", "shop_type IN ('human', 'zombie')");
            });
        });

        modelBuilder.Entity("CustomEquipment.Database.Entities.EquipmentShopProductEntity", b =>
        {
            b.Property<string>("ImplementationKey")
                .HasMaxLength(64)
                .HasColumnType("character varying(64)")
                .HasColumnName("implementation_key");

            b.Property<DateTime>("CreatedAtUtc")
                .ValueGeneratedOnAdd()
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at")
                .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.Property<string>("DisplayName")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("character varying(128)")
                .HasColumnName("display_name");

            b.Property<bool>("Enabled")
                .ValueGeneratedOnAdd()
                .HasColumnType("boolean")
                .HasColumnName("enabled")
                .HasDefaultValue(true);

            b.Property<string>("InternalName")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("character varying(128)")
                .HasColumnName("internal_name");

            b.Property<int>("SortOrder")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer")
                .HasColumnName("sort_order")
                .HasDefaultValue(0);

            b.Property<DateTime>("UpdatedAtUtc")
                .ValueGeneratedOnAdd()
                .HasColumnType("timestamp with time zone")
                .HasColumnName("updated_at")
                .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.HasKey("ImplementationKey");
            b.HasIndex("InternalName").IsUnique();

            b.ToTable("shop_products", "custom_equipment");
        });

        modelBuilder.Entity("CustomEquipment.Database.Entities.EquipmentShopRoleLimitEntity", b =>
        {
            b.Property<long>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("bigint")
                .HasColumnName("id");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

            b.Property<DateTime>("CreatedAtUtc")
                .ValueGeneratedOnAdd()
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at")
                .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.Property<bool>("Enabled")
                .ValueGeneratedOnAdd()
                .HasColumnType("boolean")
                .HasColumnName("enabled")
                .HasDefaultValue(true);

            b.Property<int>("MaxPurchasesPerMap")
                .HasColumnType("integer")
                .HasColumnName("max_purchases_per_map");

            b.Property<int>("MaxPurchasesPerRound")
                .HasColumnType("integer")
                .HasColumnName("max_purchases_per_round");

            b.Property<string>("PrivilegeKey")
                .IsRequired()
                .HasMaxLength(129)
                .HasColumnType("character varying(129)")
                .HasColumnName("privilege_key");

            b.Property<string>("ShopType")
                .IsRequired()
                .HasMaxLength(16)
                .HasColumnType("character varying(16)")
                .HasColumnName("shop_type");

            b.Property<int>("SortOrder")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer")
                .HasColumnName("sort_order")
                .HasDefaultValue(0);

            b.Property<DateTime>("UpdatedAtUtc")
                .ValueGeneratedOnAdd()
                .HasColumnType("timestamp with time zone")
                .HasColumnName("updated_at")
                .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.HasKey("Id");
            b.HasIndex("ShopType", "Enabled", "SortOrder");
            b.HasIndex("ShopType", "PrivilegeKey").IsUnique();

            b.ToTable("shop_role_limits", "custom_equipment", t =>
            {
                t.HasCheckConstraint("CK_shop_role_limits_type", "shop_type IN ('human', 'zombie')");
                t.HasCheckConstraint("CK_shop_role_limits_values", "max_purchases_per_round >= 0 AND max_purchases_per_map >= 0");
            });
        });

        modelBuilder.Entity("CustomEquipment.Database.Entities.EquipmentShopSettingsEntity", b =>
        {
            b.Property<string>("ShopType")
                .HasMaxLength(16)
                .HasColumnType("character varying(16)")
                .HasColumnName("shop_type");

            b.Property<DateTime>("CreatedAtUtc")
                .ValueGeneratedOnAdd()
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at")
                .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.Property<string>("DisplayName")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("character varying(128)")
                .HasColumnName("display_name");

            b.Property<bool>("Enabled")
                .ValueGeneratedOnAdd()
                .HasColumnType("boolean")
                .HasColumnName("enabled")
                .HasDefaultValue(true);

            b.Property<int>("MaxPurchasesPerMap")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer")
                .HasColumnName("max_purchases_per_map")
                .HasDefaultValue(0);

            b.Property<int>("MaxPurchasesPerRound")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer")
                .HasColumnName("max_purchases_per_round")
                .HasDefaultValue(0);

            b.Property<DateTime>("UpdatedAtUtc")
                .ValueGeneratedOnAdd()
                .HasColumnType("timestamp with time zone")
                .HasColumnName("updated_at")
                .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.HasKey("ShopType");

            b.ToTable("shop_settings", "custom_equipment", t =>
            {
                t.HasCheckConstraint("CK_shop_settings_limits", "max_purchases_per_round >= 0 AND max_purchases_per_map >= 0");
                t.HasCheckConstraint("CK_shop_settings_type", "shop_type IN ('human', 'zombie')");
            });
        });

        modelBuilder.Entity("CustomEquipment.Database.Entities.GameplayItemEntity", b =>
        {
            b.Property<long>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("bigint")
                .HasColumnName("id");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

            b.Property<short>("AccessFlags")
                .ValueGeneratedOnAdd()
                .HasColumnType("smallint")
                .HasColumnName("access_flags")
                .HasDefaultValue((short)1);

            b.Property<DateTime>("CreatedAtUtc")
                .ValueGeneratedOnAdd()
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at")
                .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.Property<string>("DisplayName")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("character varying(128)")
                .HasColumnName("display_name");

            b.Property<bool>("Enabled")
                .ValueGeneratedOnAdd()
                .HasColumnType("boolean")
                .HasColumnName("enabled")
                .HasDefaultValue(true);

            b.Property<string>("ImplementationKey")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("character varying(64)")
                .HasColumnName("implementation_key");

            b.Property<string>("InheritorName")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("character varying(64)")
                .HasColumnName("inheritor_name");

            b.Property<string>("InternalName")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("character varying(128)")
                .HasColumnName("internal_name");

            b.Property<int>("ItemPrice")
                .HasColumnType("integer")
                .HasColumnName("item_price");

            b.Property<string>("Model")
                .IsRequired()
                .HasMaxLength(512)
                .HasColumnType("character varying(512)")
                .HasColumnName("model");

            b.Property<string>("Rarity")
                .IsRequired()
                .ValueGeneratedOnAdd()
                .HasMaxLength(32)
                .HasColumnType("character varying(32)")
                .HasColumnName("rarity")
                .HasDefaultValue("Common");

            b.Property<string>("SettingsJson")
                .IsRequired()
                .HasColumnType("jsonb")
                .HasColumnName("settings");

            b.Property<int>("SortOrder")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer")
                .HasColumnName("sort_order")
                .HasDefaultValue(0);

            b.Property<DateTime>("UpdatedAtUtc")
                .ValueGeneratedOnAdd()
                .HasColumnType("timestamp with time zone")
                .HasColumnName("updated_at")
                .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.HasKey("Id");
            b.HasIndex("Enabled", "SortOrder");
            b.HasIndex("ImplementationKey").IsUnique();
            b.HasIndex("InternalName").IsUnique();

            b.ToTable("gameplay_items", "custom_equipment", t =>
            {
                t.HasCheckConstraint("CK_gameplay_items_access_flags", "access_flags >= 0 AND access_flags <= 3");
                t.HasCheckConstraint("CK_gameplay_items_item_price", "item_price >= 0");
                t.HasCheckConstraint("CK_gameplay_items_settings_object", "jsonb_typeof(settings) = 'object'");
            });
        });

        modelBuilder.Entity("CustomEquipment.Database.Entities.WeaponEntity", b =>
        {
            b.Property<long>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("bigint")
                .HasColumnName("id");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

            b.Property<short>("AccessFlags")
                .ValueGeneratedOnAdd()
                .HasColumnType("smallint")
                .HasColumnName("access_flags")
                .HasDefaultValue((short)1);

            b.Property<int?>("AmmoPrice").HasColumnType("integer").HasColumnName("ammo_price");
            b.Property<int?>("ClipSize").HasColumnType("integer").HasColumnName("clip_size");
            b.Property<float?>("CycleTimePrimary").HasColumnType("real").HasColumnName("cycle_time_primary");
            b.Property<float?>("CycleTimeSecondary").HasColumnType("real").HasColumnName("cycle_time_secondary");

            b.Property<DateTime>("CreatedAtUtc")
                .ValueGeneratedOnAdd()
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at")
                .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.Property<float?>("DamageChest").HasColumnType("real").HasColumnName("damage_chest");
            b.Property<float?>("DamageHead").HasColumnType("real").HasColumnName("damage_head");
            b.Property<float?>("DamageLeftArm").HasColumnType("real").HasColumnName("damage_left_arm");
            b.Property<float?>("DamageLeftLeg").HasColumnType("real").HasColumnName("damage_left_leg");
            b.Property<float?>("DamageNeck").HasColumnType("real").HasColumnName("damage_neck");
            b.Property<float?>("DamageRightArm").HasColumnType("real").HasColumnName("damage_right_arm");
            b.Property<float?>("DamageRightLeg").HasColumnType("real").HasColumnName("damage_right_leg");
            b.Property<float?>("DamageStomach").HasColumnType("real").HasColumnName("damage_stomach");
            b.Property<float?>("DeployDuration").HasColumnType("real").HasColumnName("deploy_duration");

            b.Property<string>("DisplayName")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("character varying(128)")
                .HasColumnName("display_name");

            b.Property<float?>("EffectiveRange").HasColumnType("real").HasColumnName("effective_range");

            b.Property<bool>("Enabled")
                .ValueGeneratedOnAdd()
                .HasColumnType("boolean")
                .HasColumnName("enabled")
                .HasDefaultValue(true);

            b.Property<string>("InheritorName")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("character varying(64)")
                .HasColumnName("inheritor_name");

            b.Property<string>("InternalName")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("character varying(128)")
                .HasColumnName("internal_name");

            b.Property<int>("ItemPrice").HasColumnType("integer").HasColumnName("item_price");

            b.Property<string>("Model")
                .IsRequired()
                .HasMaxLength(512)
                .HasColumnType("character varying(512)")
                .HasColumnName("model");

            b.Property<int?>("NumBullets").HasColumnType("integer").HasColumnName("num_bullets");
            b.Property<string>("ParticleImpact").HasMaxLength(512).HasColumnType("character varying(512)").HasColumnName("particle_impact");
            b.Property<string>("ParticleMuzzleFlash").HasMaxLength(512).HasColumnType("character varying(512)").HasColumnName("particle_muzzle_flash");
            b.Property<string>("ParticleTracer").HasMaxLength(512).HasColumnType("character varying(512)").HasColumnName("particle_tracer");
            b.Property<float?>("Penetration").HasColumnType("real").HasColumnName("penetration");
            b.Property<float?>("RangeModifier").HasColumnType("real").HasColumnName("range_modifier");

            b.Property<string>("Rarity")
                .IsRequired()
                .ValueGeneratedOnAdd()
                .HasMaxLength(32)
                .HasColumnType("character varying(32)")
                .HasColumnName("rarity")
                .HasDefaultValue("Common");

            b.Property<int?>("ReserveAmmo").HasColumnType("integer").HasColumnName("reserve_ammo");

            b.Property<string>("Slot")
                .IsRequired()
                .HasMaxLength(32)
                .HasColumnType("character varying(32)")
                .HasColumnName("slot");

            b.Property<int>("SortOrder")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer")
                .HasColumnName("sort_order")
                .HasDefaultValue(0);

            b.Property<string>("SubclassName")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("character varying(128)")
                .HasColumnName("subclass_name");

            b.Property<DateTime>("UpdatedAtUtc")
                .ValueGeneratedOnAdd()
                .HasColumnType("timestamp with time zone")
                .HasColumnName("updated_at")
                .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.Property<string>("WeaponType")
                .IsRequired()
                .HasMaxLength(32)
                .HasColumnType("character varying(32)")
                .HasColumnName("weapon_type");

            b.HasKey("Id");
            b.HasIndex("Enabled", "SortOrder");
            b.HasIndex("InternalName").IsUnique();

            b.ToTable("weapons", "custom_equipment", t =>
            {
                t.HasCheckConstraint("CK_weapons_access_flags", "access_flags >= 0 AND access_flags <= 3");
                t.HasCheckConstraint("CK_weapons_ammo_price", "ammo_price IS NULL OR ammo_price >= 0");
                t.HasCheckConstraint("CK_weapons_ammunition", "(clip_size IS NULL OR clip_size >= 0) AND (reserve_ammo IS NULL OR reserve_ammo >= 0)");
                t.HasCheckConstraint("CK_weapons_ballistics", "(num_bullets IS NULL OR num_bullets >= 1) AND (penetration IS NULL OR penetration >= 0) AND (effective_range IS NULL OR effective_range >= 0) AND (range_modifier IS NULL OR range_modifier >= 0)");
                t.HasCheckConstraint("CK_weapons_damage", "(damage_head IS NULL OR damage_head >= 0) AND (damage_chest IS NULL OR damage_chest >= 0) AND (damage_stomach IS NULL OR damage_stomach >= 0) AND (damage_left_arm IS NULL OR damage_left_arm >= 0) AND (damage_right_arm IS NULL OR damage_right_arm >= 0) AND (damage_left_leg IS NULL OR damage_left_leg >= 0) AND (damage_right_leg IS NULL OR damage_right_leg >= 0) AND (damage_neck IS NULL OR damage_neck >= 0)");
                t.HasCheckConstraint("CK_weapons_item_price", "item_price >= 0");
                t.HasCheckConstraint("CK_weapons_timing", "(cycle_time_primary IS NULL OR cycle_time_primary > 0) AND (cycle_time_secondary IS NULL OR (cycle_time_secondary > 0 AND cycle_time_primary IS NOT NULL)) AND (deploy_duration IS NULL OR deploy_duration >= 0)");
            });
        });

        modelBuilder.Entity("CustomEquipment.Database.Entities.EquipmentShopListingEntity", b =>
        {
            b.HasOne("CustomEquipment.Database.Entities.EquipmentShopCategoryEntity", "Category")
                .WithMany("Listings")
                .HasForeignKey("CategoryId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.Navigation("Category");
        });

        modelBuilder.Entity("CustomEquipment.Database.Entities.WeaponSoundEntity", b =>
        {
            b.Property<long>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("bigint")
                .HasColumnName("id");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

            b.Property<DateTime>("CreatedAtUtc")
                .ValueGeneratedOnAdd()
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at")
                .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.Property<bool>("Enabled")
                .ValueGeneratedOnAdd()
                .HasColumnType("boolean")
                .HasColumnName("enabled")
                .HasDefaultValue(true);

            b.Property<string>("EventName")
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnType("character varying(256)")
                .HasColumnName("event_name");

            b.Property<string>("ExtraPropertiesJson").HasColumnType("jsonb").HasColumnName("extra_properties");

            b.Property<string>("MixGroup")
                .IsRequired()
                .ValueGeneratedOnAdd()
                .HasMaxLength(64)
                .HasColumnType("character varying(64)")
                .HasColumnName("mix_group")
                .HasDefaultValue("Weapons");

            b.Property<float>("Pitch")
                .ValueGeneratedOnAdd()
                .HasColumnType("real")
                .HasColumnName("pitch")
                .HasDefaultValue(1f);

            b.Property<bool>("PreloadVsnds")
                .ValueGeneratedOnAdd()
                .HasColumnType("boolean")
                .HasColumnName("preload_vsnds")
                .HasDefaultValue(true);

            b.Property<string>("ReplacesEventName")
                .HasMaxLength(256)
                .HasColumnType("character varying(256)")
                .HasColumnName("replaces_event_name");

            b.Property<string>("SoundType")
                .IsRequired()
                .ValueGeneratedOnAdd()
                .HasMaxLength(64)
                .HasColumnType("character varying(64)")
                .HasColumnName("sound_type")
                .HasDefaultValue("csgo_mega");

            b.Property<int>("SortOrder")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer")
                .HasColumnName("sort_order")
                .HasDefaultValue(0);

            b.Property<string>("Trigger")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("character varying(64)")
                .HasColumnName("trigger");

            b.Property<DateTime>("UpdatedAtUtc")
                .ValueGeneratedOnAdd()
                .HasColumnType("timestamp with time zone")
                .HasColumnName("updated_at")
                .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.Property<float>("Volume")
                .ValueGeneratedOnAdd()
                .HasColumnType("real")
                .HasColumnName("volume")
                .HasDefaultValue(1f);

            b.Property<long>("WeaponId").HasColumnType("bigint").HasColumnName("weapon_id");

            b.HasKey("Id");
            b.HasIndex("EventName").IsUnique();
            b.HasIndex("WeaponId", "Trigger").IsUnique();

            b.ToTable("weapon_sounds", "custom_equipment", t =>
            {
                t.HasCheckConstraint("CK_weapon_sounds_pitch", "pitch > 0");
                t.HasCheckConstraint("CK_weapon_sounds_volume", "volume >= 0");
            });
        });

        modelBuilder.Entity("CustomEquipment.Database.Entities.WeaponSoundFileEntity", b =>
        {
            b.Property<long>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("bigint")
                .HasColumnName("id");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

            b.Property<string>("FilePath")
                .IsRequired()
                .HasMaxLength(512)
                .HasColumnType("character varying(512)")
                .HasColumnName("file_path");

            b.Property<long>("SoundId").HasColumnType("bigint").HasColumnName("sound_id");

            b.Property<int>("SortOrder")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer")
                .HasColumnName("sort_order")
                .HasDefaultValue(0);

            b.Property<int>("Track")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer")
                .HasColumnName("track")
                .HasDefaultValue(1);

            b.HasKey("Id");
            b.HasIndex("SoundId", "Track", "SortOrder");

            b.ToTable("weapon_sound_files", "custom_equipment", t =>
            {
                t.HasCheckConstraint("CK_weapon_sound_files_track", "track >= 1 AND track <= 99");
            });
        });

        modelBuilder.Entity("CustomEquipment.Database.Entities.WeaponSoundEntity", b =>
        {
            b.HasOne("CustomEquipment.Database.Entities.WeaponEntity", "Weapon")
                .WithMany("Sounds")
                .HasForeignKey("WeaponId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("Weapon");
        });

        modelBuilder.Entity("CustomEquipment.Database.Entities.WeaponSoundFileEntity", b =>
        {
            b.HasOne("CustomEquipment.Database.Entities.WeaponSoundEntity", "Sound")
                .WithMany("Files")
                .HasForeignKey("SoundId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("Sound");
        });

        modelBuilder.Entity("CustomEquipment.Database.Entities.EquipmentShopCategoryEntity", b =>
        {
            b.Navigation("Listings");
        });

        modelBuilder.Entity("CustomEquipment.Database.Entities.WeaponEntity", b =>
        {
            b.Navigation("Sounds");
        });

        modelBuilder.Entity("CustomEquipment.Database.Entities.WeaponSoundEntity", b =>
        {
            b.Navigation("Files");
        });
#pragma warning restore 612, 618
    }
}
