<Project>
    <PropertyGroup>
        <IsCoreProject>$([System.Text.RegularExpressions.Regex]::IsMatch('$(MSBuildProjectName)', '(\.Core|Core)$'))</IsCoreProject>
        <IsApiProject>$([System.Text.RegularExpressions.Regex]::IsMatch('$(MSBuildProjectName)', '(\.Api|Api)$'))</IsApiProject>
        <IsCommonProject>$([System.Text.RegularExpressions.Regex]::IsMatch('$(MSBuildProjectName)', '^Common\.'))</IsCommonProject>

        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>

        <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
        <GenerateDependencyFile>true</GenerateDependencyFile>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
        <DebugSymbols>true</DebugSymbols>
        <DebugType>portable</DebugType>
    </PropertyGroup>

    <PropertyGroup Condition="'$(IsApiProject)' == 'True' or '$(MSBuildProjectName)' == 'Common.Hooks'">
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);1591</NoWarn>
    </PropertyGroup>

    <!-- Папка output создаётся только для Core -->
    <PropertyGroup Condition="'$(IsCoreProject)' == 'True'">
        <OutputPath>$(MSBuildThisFileDirectory)output\$(MSBuildProjectName)\</OutputPath>
        <OutDir>$(OutputPath)</OutDir>
    </PropertyGroup>

    <ItemDefinitionGroup>
        <ProjectReference>
            <Private>false</Private>
        </ProjectReference>

        <Reference>
            <Private>false</Private>
        </Reference>
    </ItemDefinitionGroup>
</Project>
