<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <PublishDir>$(OutputPath)publish/RoundRatingNotify</PublishDir>
        <PackageId>RoundRatingNotify.Core</PackageId>
        <RootNamespace>RoundRatingNotify</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" ExcludeAssets="runtime" PrivateAssets="all"/>
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.0" ExcludeAssets="runtime" PrivateAssets="all"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.0" ExcludeAssets="runtime" PrivateAssets="all"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.0" ExcludeAssets="runtime" PrivateAssets="all"/>
        <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.0" ExcludeAssets="runtime" PrivateAssets="all"/>
        <PackageReference Include="SwiftlyS2.CS2" Version="1.4.5-beta.16" ExcludeAssets="runtime" PrivateAssets="all">
          <IncludeAssets>compile; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <Content Include="resources/gamedata/**/*;resources/templates/**/*;resources/translations/**/*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="examples\**\*.cs"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Common.Di\Common.Di.csproj" />
      <ProjectReference Include="..\ZombiePlague.Api\ZombiePlague.Api.csproj" />
    </ItemGroup>

    <Target Name="CreateZip" AfterTargets="Publish">
        <ItemGroup>
            <PublishFiles Include="$(PublishDir)**\*.*"/>
        </ItemGroup>

        <ZipDirectory SourceDirectory="$(PublishDir)../" DestinationFile="$(OutputPath)../$(AssemblyName).zip" Overwrite="true"/>
    </Target>

</Project> 
