<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
        <PackageReference Include="SwiftlyS2.CS2" Version="1.4.9" PrivateAssets="all" />
        <PackageReference Include="xunit" Version="2.9.3" />
        <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <ProjectReference Include="../CustomHud.Api/CustomHud.Api.csproj" Private="true" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Common.Hooks\Common.Hooks.csproj" Private="true" />
        <ProjectReference Include="..\CustomEquipment.Api\CustomEquipment.Api.csproj" Private="true" />
        <ProjectReference Include="..\Economy.Api\Economy.Api.csproj" Private="true" />
        <ProjectReference Include="..\Localization.Api\Localization.Api.csproj" Private="true" />
        <ProjectReference Include="..\Shop.Api\Shop.Api.csproj">
            <Private>true</Private>
        </ProjectReference>
        <ProjectReference Include="..\Shop.Core\Shop.Core.csproj">
            <Private>true</Private>
        </ProjectReference>
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\Shop.Core\resources\templates\template.jsonc" Link="Fixtures\template.jsonc" CopyToOutputDirectory="PreserveNewest" />
        <Content Include="../Shop.Core/resources/hud/shop/content/panorama/layout/custom_game/elysium_shop_v4_r2.xml" Link="Fixtures/elysium_shop_v4_r2.xml" CopyToOutputDirectory="PreserveNewest" />
        <Content Include="../Shop.Core/resources/hud/shop/content/panorama/styles/custom_game/elysium_shop_v4_r2.css" Link="Fixtures/elysium_shop_v4_r2.css" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

</Project>
