<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="SwiftlyS2.CS2" Version="1.4.0-beta.37" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="Events\**" />
      <Compile Include="Events\EventDelegates.cs" />
      <Compile Include="Events\EventService.cs" />
      <Compile Include="Events\IEventPublisher.cs" />
      <Compile Include="Events\IEventSubscriber.cs" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Remove="Events\**" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Events\**" />
    </ItemGroup>

</Project>
