using Economy.Core.Database;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Economy.Core.src.Database.Migrations;

[DbContext(typeof(EconomyDbContext))]
[Migration("20260830113000_AddEconomyRules")]
public sealed class AddEconomyRules : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            CREATE TABLE IF NOT EXISTS economy.settings (
                id smallint PRIMARY KEY DEFAULT 1,
                revision bigint NOT NULL DEFAULT 1,
                absolute_max_money integer NOT NULL DEFAULT 99999,
                default_max_money integer NOT NULL DEFAULT 99999,
                start_money integer NOT NULL DEFAULT 5000,
                money_per_damage numeric(12,4) NOT NULL DEFAULT 0.5,
                money_for_infection integer NOT NULL DEFAULT 500,
                money_for_zombie_kill integer NOT NULL DEFAULT 0,
                money_for_human_kill integer NOT NULL DEFAULT 0,
                save_on_round_end boolean NOT NULL DEFAULT false,
                save_on_disconnect boolean NOT NULL DEFAULT true,
                save_on_unload boolean NOT NULL DEFAULT true,
                periodic_save_enabled boolean NOT NULL DEFAULT false,
                periodic_save_interval_seconds integer NOT NULL DEFAULT 300,
                settings_refresh_interval_seconds integer NOT NULL DEFAULT 30,
                updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT ck_economy_settings_singleton CHECK (id = 1),
                CONSTRAINT ck_economy_settings_limits CHECK (
                    absolute_max_money >= 0
                    AND default_max_money BETWEEN 0 AND absolute_max_money
                    AND start_money BETWEEN 0 AND default_max_money
                ),
                CONSTRAINT ck_economy_settings_rewards CHECK (
                    money_per_damage >= 0
                    AND money_for_infection >= 0
                    AND money_for_zombie_kill >= 0
                    AND money_for_human_kill >= 0
                ),
                CONSTRAINT ck_economy_settings_intervals CHECK (
                    periodic_save_interval_seconds BETWEEN 10 AND 86400
                    AND settings_refresh_interval_seconds BETWEEN 10 AND 3600
                )
            );

            INSERT INTO economy.settings (id)
            VALUES (1)
            ON CONFLICT (id) DO NOTHING;

            CREATE TABLE IF NOT EXISTS economy.role_rules (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                privilege_key varchar(129) NOT NULL,
                max_money integer NOT NULL,
                reward_bonus_percent numeric(8,2) NOT NULL DEFAULT 0,
                enabled boolean NOT NULL DEFAULT true,
                created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT ck_economy_role_rules_values CHECK (
                    max_money >= 0 AND reward_bonus_percent BETWEEN 0 AND 10000
                )
            );

            DO $migration$
            BEGIN
                IF to_regclass('economy.ux_economy_role_rules_privilege_key') IS NULL THEN
                    EXECUTE 'CREATE UNIQUE INDEX ux_economy_role_rules_privilege_key '
                        || 'ON economy.role_rules (privilege_key)';
                END IF;
            END;
            $migration$;

            CREATE TABLE IF NOT EXISTS economy.weapon_reward_rules (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                weapon_key varchar(128) NOT NULL,
                damage_bonus_percent numeric(8,2) NOT NULL DEFAULT 0,
                enabled boolean NOT NULL DEFAULT true,
                created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT ck_economy_weapon_reward_rules_values CHECK (
                    damage_bonus_percent BETWEEN 0 AND 10000
                )
            );

            DO $migration$
            BEGIN
                IF to_regclass('economy.ux_economy_weapon_reward_rules_weapon_key') IS NULL THEN
                    EXECUTE 'CREATE UNIQUE INDEX ux_economy_weapon_reward_rules_weapon_key '
                        || 'ON economy.weapon_reward_rules (weapon_key)';
                END IF;
            END;
            $migration$;

            DO $migration$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_proc proc
                    INNER JOIN pg_namespace ns ON ns.oid = proc.pronamespace
                    WHERE ns.nspname = 'economy'
                      AND proc.proname = 'bump_settings_revision'
                      AND proc.pronargs = 0
                ) THEN
                    EXECUTE $ddl$
                        CREATE FUNCTION economy.bump_settings_revision()
                        RETURNS trigger
                        LANGUAGE plpgsql
                        AS $function$
                        BEGIN
                            UPDATE economy.settings
                            SET revision = revision + 1,
                                updated_at = CURRENT_TIMESTAMP
                            WHERE id = 1;
                            RETURN NULL;
                        END;
                        $function$
                    $ddl$;
                END IF;
            END;
            $migration$;

            DO $migration$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_trigger
                    WHERE tgname = 'trg_economy_role_rules_revision'
                      AND tgrelid = 'economy.role_rules'::regclass
                      AND NOT tgisinternal
                ) THEN
                    EXECUTE 'CREATE TRIGGER trg_economy_role_rules_revision '
                        || 'AFTER INSERT OR UPDATE OR DELETE ON economy.role_rules '
                        || 'FOR EACH STATEMENT EXECUTE FUNCTION economy.bump_settings_revision()';
                END IF;
            END;
            $migration$;

            DO $migration$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_trigger
                    WHERE tgname = 'trg_economy_weapon_rules_revision'
                      AND tgrelid = 'economy.weapon_reward_rules'::regclass
                      AND NOT tgisinternal
                ) THEN
                    EXECUTE 'CREATE TRIGGER trg_economy_weapon_rules_revision '
                        || 'AFTER INSERT OR UPDATE OR DELETE ON economy.weapon_reward_rules '
                        || 'FOR EACH STATEMENT EXECUTE FUNCTION economy.bump_settings_revision()';
                END IF;
            END;
            $migration$;
            """
        );
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            DROP TRIGGER IF EXISTS trg_economy_weapon_rules_revision ON economy.weapon_reward_rules;
            DROP TRIGGER IF EXISTS trg_economy_role_rules_revision ON economy.role_rules;
            DROP FUNCTION IF EXISTS economy.bump_settings_revision();
            DROP TABLE IF EXISTS economy.weapon_reward_rules;
            DROP TABLE IF EXISTS economy.role_rules;
            DROP TABLE IF EXISTS economy.settings;
            """
        );
    }
}
