using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Menu.Core.Database.Migrations;

[DbContext(typeof(MenuDbContext))]
[Migration("20260830090000_InitialMenuCore")]
internal sealed class InitialMenuCore : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            CREATE SCHEMA IF NOT EXISTS menu;

            CREATE TABLE menu.providers (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                provider_key VARCHAR(128) NOT NULL,
                display_name VARCHAR(128) NOT NULL,
                metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
                created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT pk_menu_providers PRIMARY KEY (id),
                CONSTRAINT ck_menu_providers_key
                    CHECK (provider_key ~ '^[a-z0-9][a-z0-9_.-]{0,127}$'),
                CONSTRAINT ck_menu_providers_metadata
                    CHECK (jsonb_typeof(metadata) = 'object')
            );

            CREATE UNIQUE INDEX ux_menu_providers_key
                ON menu.providers (provider_key);
            CREATE INDEX ix_menu_providers_updated_at
                ON menu.providers (updated_at);

            CREATE TABLE menu.provider_instances (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                provider_id BIGINT NOT NULL,
                server_key VARCHAR(64) NOT NULL,
                plugin_version VARCHAR(32) NOT NULL,
                menu_api_version INTEGER NOT NULL,
                status VARCHAR(32) NOT NULL DEFAULT 'offline',
                capabilities JSONB NOT NULL DEFAULT '[]'::jsonb,
                metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
                session_id UUID NOT NULL,
                generation BIGINT NOT NULL DEFAULT 1,
                registered_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                last_seen_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                offline_at TIMESTAMPTZ NULL,
                updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                last_error TEXT NULL,
                CONSTRAINT pk_menu_provider_instances PRIMARY KEY (id),
                CONSTRAINT fk_menu_provider_instances_provider
                    FOREIGN KEY (provider_id) REFERENCES menu.providers(id) ON DELETE RESTRICT,
                CONSTRAINT ck_menu_provider_instances_server_key
                    CHECK (server_key ~ '^[A-Za-z0-9][A-Za-z0-9_.-]{0,63}$'),
                CONSTRAINT ck_menu_provider_instances_status
                    CHECK (status IN ('online','offline','incompatible','api_outdated','error')),
                CONSTRAINT ck_menu_provider_instances_api_version
                    CHECK (menu_api_version > 0),
                CONSTRAINT ck_menu_provider_instances_generation
                    CHECK (generation > 0),
                CONSTRAINT ck_menu_provider_instances_capabilities
                    CHECK (jsonb_typeof(capabilities) = 'array'),
                CONSTRAINT ck_menu_provider_instances_metadata
                    CHECK (jsonb_typeof(metadata) = 'object')
            );

            CREATE UNIQUE INDEX ux_menu_provider_instances_provider_server
                ON menu.provider_instances (provider_id, server_key);
            CREATE INDEX ix_menu_provider_instances_session
                ON menu.provider_instances (session_id);
            CREATE INDEX ix_menu_provider_instances_server_status_seen
                ON menu.provider_instances (server_key, status, last_seen_at);

            CREATE TABLE menu.provider_exports (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                provider_instance_id BIGINT NOT NULL,
                export_type VARCHAR(16) NOT NULL,
                export_key VARCHAR(128) NOT NULL,
                display_name VARCHAR(128) NOT NULL,
                schema JSONB NULL,
                metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
                is_declared BOOLEAN NOT NULL DEFAULT TRUE,
                declared_generation BIGINT NOT NULL,
                first_seen_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                last_seen_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT pk_menu_provider_exports PRIMARY KEY (id),
                CONSTRAINT fk_menu_provider_exports_instance
                    FOREIGN KEY (provider_instance_id)
                    REFERENCES menu.provider_instances(id) ON DELETE RESTRICT,
                CONSTRAINT ck_menu_provider_exports_type
                    CHECK (export_type IN ('menu','action')),
                CONSTRAINT ck_menu_provider_exports_key
                    CHECK (export_key ~ '^[a-z0-9][a-z0-9_.-]{0,127}$'),
                CONSTRAINT ck_menu_provider_exports_generation
                    CHECK (declared_generation > 0),
                CONSTRAINT ck_menu_provider_exports_schema
                    CHECK (schema IS NULL OR jsonb_typeof(schema) = 'object'),
                CONSTRAINT ck_menu_provider_exports_metadata
                    CHECK (jsonb_typeof(metadata) = 'object')
            );

            CREATE UNIQUE INDEX ux_menu_provider_exports_instance_type_key
                ON menu.provider_exports (provider_instance_id, export_type, export_key);
            CREATE INDEX ix_menu_provider_exports_declared
                ON menu.provider_exports (provider_instance_id, is_declared);

            CREATE TABLE menu.definitions (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                menu_key VARCHAR(128) NOT NULL,
                title VARCHAR(128) NOT NULL,
                description TEXT NULL,
                owner_provider_key VARCHAR(128) NULL,
                status VARCHAR(16) NOT NULL DEFAULT 'draft',
                created_by VARCHAR(128) NULL,
                updated_by VARCHAR(128) NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT pk_menu_definitions PRIMARY KEY (id),
                CONSTRAINT ck_menu_definitions_key
                    CHECK (menu_key ~ '^[a-z0-9][a-z0-9_.-]{0,127}$'),
                CONSTRAINT ck_menu_definitions_owner_provider
                    CHECK (owner_provider_key IS NULL
                        OR owner_provider_key ~ '^[a-z0-9][a-z0-9_.-]{0,127}$'),
                CONSTRAINT ck_menu_definitions_status
                    CHECK (status IN ('draft','published','archived'))
            );

            CREATE UNIQUE INDEX ux_menu_definitions_key
                ON menu.definitions (menu_key);
            CREATE INDEX ix_menu_definitions_status_updated
                ON menu.definitions (status, updated_at);

            CREATE TABLE menu.revisions (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                definition_id BIGINT NOT NULL,
                revision_number INTEGER NOT NULL,
                schema_version INTEGER NOT NULL,
                payload JSONB NOT NULL,
                checksum CHARACTER(64) NOT NULL,
                based_on_revision_id BIGINT NULL,
                created_by VARCHAR(128) NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                published_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT pk_menu_revisions PRIMARY KEY (id),
                CONSTRAINT ak_menu_revisions_id_definition UNIQUE (id, definition_id),
                CONSTRAINT fk_menu_revisions_definition
                    FOREIGN KEY (definition_id) REFERENCES menu.definitions(id) ON DELETE RESTRICT,
                CONSTRAINT fk_menu_revisions_based_on
                    FOREIGN KEY (based_on_revision_id, definition_id)
                    REFERENCES menu.revisions(id, definition_id) ON DELETE RESTRICT,
                CONSTRAINT ck_menu_revisions_number CHECK (revision_number > 0),
                CONSTRAINT ck_menu_revisions_schema_version CHECK (schema_version > 0),
                CONSTRAINT ck_menu_revisions_payload CHECK (jsonb_typeof(payload) = 'object'),
                CONSTRAINT ck_menu_revisions_checksum CHECK (checksum ~ '^[0-9a-f]{64}$')
            );

            CREATE UNIQUE INDEX ux_menu_revisions_definition_number
                ON menu.revisions (definition_id, revision_number);
            CREATE INDEX ix_menu_revisions_definition_published
                ON menu.revisions (definition_id ASC, published_at DESC);
            CREATE INDEX ix_menu_revisions_based_on
                ON menu.revisions (based_on_revision_id, definition_id);

            CREATE TABLE menu.drafts (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                definition_id BIGINT NOT NULL,
                base_revision_id BIGINT NULL,
                schema_version INTEGER NOT NULL,
                payload JSONB NOT NULL,
                lock_version BIGINT NOT NULL DEFAULT 0,
                created_by VARCHAR(128) NULL,
                updated_by VARCHAR(128) NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT pk_menu_drafts PRIMARY KEY (id),
                CONSTRAINT fk_menu_drafts_definition
                    FOREIGN KEY (definition_id) REFERENCES menu.definitions(id) ON DELETE CASCADE,
                CONSTRAINT fk_menu_drafts_base_revision
                    FOREIGN KEY (base_revision_id, definition_id)
                    REFERENCES menu.revisions(id, definition_id) ON DELETE RESTRICT,
                CONSTRAINT ck_menu_drafts_schema_version CHECK (schema_version > 0),
                CONSTRAINT ck_menu_drafts_payload CHECK (jsonb_typeof(payload) = 'object'),
                CONSTRAINT ck_menu_drafts_lock_version CHECK (lock_version >= 0)
            );

            CREATE UNIQUE INDEX ux_menu_drafts_definition
                ON menu.drafts (definition_id);
            CREATE INDEX ix_menu_drafts_updated_at
                ON menu.drafts (updated_at);
            CREATE INDEX ix_menu_drafts_base_revision
                ON menu.drafts (base_revision_id, definition_id);

            CREATE TABLE menu.releases (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                release_number BIGINT NOT NULL,
                schema_version INTEGER NOT NULL,
                menu_core_api_version INTEGER NOT NULL,
                rollback_of_release_id BIGINT NULL,
                created_by VARCHAR(128) NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                published_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT pk_menu_releases PRIMARY KEY (id),
                CONSTRAINT fk_menu_releases_rollback_of
                    FOREIGN KEY (rollback_of_release_id) REFERENCES menu.releases(id) ON DELETE RESTRICT,
                CONSTRAINT ck_menu_releases_number CHECK (release_number > 0),
                CONSTRAINT ck_menu_releases_schema_version CHECK (schema_version > 0),
                CONSTRAINT ck_menu_releases_api_version CHECK (menu_core_api_version > 0)
            );

            CREATE UNIQUE INDEX ux_menu_releases_number
                ON menu.releases (release_number);
            CREATE INDEX ix_menu_releases_published_at
                ON menu.releases (published_at DESC);
            CREATE INDEX ix_menu_releases_rollback_of
                ON menu.releases (rollback_of_release_id);

            CREATE TABLE menu.release_items (
                release_id BIGINT NOT NULL,
                definition_id BIGINT NOT NULL,
                revision_id BIGINT NOT NULL,
                CONSTRAINT pk_menu_release_items PRIMARY KEY (release_id, definition_id),
                CONSTRAINT ak_menu_release_items_release_revision
                    UNIQUE (release_id, revision_id),
                CONSTRAINT fk_menu_release_items_release
                    FOREIGN KEY (release_id) REFERENCES menu.releases(id) ON DELETE RESTRICT,
                CONSTRAINT fk_menu_release_items_definition
                    FOREIGN KEY (definition_id) REFERENCES menu.definitions(id) ON DELETE RESTRICT,
                CONSTRAINT fk_menu_release_items_revision
                    FOREIGN KEY (revision_id, definition_id)
                    REFERENCES menu.revisions(id, definition_id) ON DELETE RESTRICT
            );

            CREATE INDEX ix_menu_release_items_definition
                ON menu.release_items (definition_id);
            CREATE INDEX ix_menu_release_items_revision
                ON menu.release_items (revision_id, definition_id);

            CREATE TABLE menu.release_targets (
                release_id BIGINT NOT NULL,
                server_key VARCHAR(64) NOT NULL,
                server_group_key VARCHAR(64) NULL,
                artifact_json TEXT NOT NULL,
                checksum CHARACTER(64) NOT NULL,
                capability_manifest JSONB NOT NULL DEFAULT '{}'::jsonb,
                created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT pk_menu_release_targets PRIMARY KEY (release_id, server_key),
                CONSTRAINT fk_menu_release_targets_release
                    FOREIGN KEY (release_id) REFERENCES menu.releases(id) ON DELETE RESTRICT,
                CONSTRAINT ck_menu_release_targets_server
                    CHECK (server_key ~ '^[A-Za-z0-9][A-Za-z0-9_.-]{0,63}$'),
                CONSTRAINT ck_menu_release_targets_server_group
                    CHECK (server_group_key IS NULL
                        OR server_group_key ~ '^[A-Za-z0-9][A-Za-z0-9_.-]{0,63}$'),
                CONSTRAINT ck_menu_release_targets_artifact
                    CHECK (jsonb_typeof(artifact_json::jsonb) = 'object'),
                CONSTRAINT ck_menu_release_targets_checksum
                    CHECK (checksum ~ '^[0-9a-f]{64}$'),
                CONSTRAINT ck_menu_release_targets_capabilities
                    CHECK (jsonb_typeof(capability_manifest) = 'object')
            );

            CREATE INDEX ix_menu_release_targets_server_release
                ON menu.release_targets (server_key, release_id);
            CREATE INDEX ix_menu_release_targets_checksum
                ON menu.release_targets (checksum);

            CREATE TABLE menu.release_heads (
                server_key VARCHAR(64) NOT NULL,
                release_id BIGINT NOT NULL,
                lock_version BIGINT NOT NULL DEFAULT 0,
                updated_by VARCHAR(128) NULL,
                updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT pk_menu_release_heads PRIMARY KEY (server_key),
                CONSTRAINT fk_menu_release_heads_target
                    FOREIGN KEY (release_id, server_key)
                    REFERENCES menu.release_targets(release_id, server_key) ON DELETE RESTRICT,
                CONSTRAINT ck_menu_release_heads_server
                    CHECK (server_key ~ '^[A-Za-z0-9][A-Za-z0-9_.-]{0,63}$'),
                CONSTRAINT ck_menu_release_heads_lock_version CHECK (lock_version >= 0)
            );

            CREATE INDEX ix_menu_release_heads_release
                ON menu.release_heads (release_id, server_key);

            CREATE TABLE menu.commands (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                release_id BIGINT NOT NULL,
                server_key VARCHAR(64) NOT NULL,
                revision_id BIGINT NOT NULL,
                menu_key VARCHAR(128) NOT NULL,
                command_type VARCHAR(16) NOT NULL,
                alias VARCHAR(128) NOT NULL,
                normalized_alias VARCHAR(128) NOT NULL,
                suppression_mode VARCHAR(16) NOT NULL DEFAULT 'none',
                enabled BOOLEAN NOT NULL DEFAULT TRUE,
                created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT pk_menu_commands PRIMARY KEY (id),
                CONSTRAINT fk_menu_commands_target
                    FOREIGN KEY (release_id, server_key)
                    REFERENCES menu.release_targets(release_id, server_key) ON DELETE RESTRICT,
                CONSTRAINT fk_menu_commands_release_item
                    FOREIGN KEY (release_id, revision_id)
                    REFERENCES menu.release_items(release_id, revision_id) ON DELETE RESTRICT,
                CONSTRAINT ck_menu_commands_server
                    CHECK (server_key ~ '^[A-Za-z0-9][A-Za-z0-9_.-]{0,63}$'),
                CONSTRAINT ck_menu_commands_menu_key
                    CHECK (menu_key ~ '^[a-z0-9][a-z0-9_.-]{0,127}$'),
                CONSTRAINT ck_menu_commands_type CHECK (command_type IN ('chat','console')),
                CONSTRAINT ck_menu_commands_alias
                    CHECK (btrim(alias) <> '' AND btrim(normalized_alias) <> ''),
                CONSTRAINT ck_menu_commands_suppression
                    CHECK (suppression_mode IN ('none','on_match','on_success'))
            );

            CREATE UNIQUE INDEX ux_menu_commands_active_route
                ON menu.commands (release_id, server_key, command_type, normalized_alias)
                WHERE enabled = TRUE;
            CREATE INDEX ix_menu_commands_revision
                ON menu.commands (revision_id);
            CREATE INDEX ix_menu_commands_target
                ON menu.commands (release_id, server_key);
            CREATE INDEX ix_menu_commands_release_item
                ON menu.commands (release_id, revision_id);
            CREATE INDEX ix_menu_commands_server_lookup
                ON menu.commands (server_key, command_type, normalized_alias)
                WHERE enabled = TRUE;

            CREATE TABLE menu.audit_log (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                actor_id VARCHAR(128) NULL,
                actor_display_name VARCHAR(128) NULL,
                action VARCHAR(64) NOT NULL,
                entity_type VARCHAR(32) NOT NULL,
                entity_key VARCHAR(128) NULL,
                server_key VARCHAR(64) NULL,
                release_id BIGINT NULL,
                revision_id BIGINT NULL,
                changes JSONB NOT NULL DEFAULT '{}'::jsonb,
                metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
                created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT pk_menu_audit_log PRIMARY KEY (id),
                CONSTRAINT fk_menu_audit_release
                    FOREIGN KEY (release_id) REFERENCES menu.releases(id) ON DELETE RESTRICT,
                CONSTRAINT fk_menu_audit_revision
                    FOREIGN KEY (revision_id) REFERENCES menu.revisions(id) ON DELETE RESTRICT,
                CONSTRAINT ck_menu_audit_action CHECK (btrim(action) <> ''),
                CONSTRAINT ck_menu_audit_entity_type CHECK (btrim(entity_type) <> ''),
                CONSTRAINT ck_menu_audit_changes CHECK (jsonb_typeof(changes) = 'object'),
                CONSTRAINT ck_menu_audit_metadata CHECK (jsonb_typeof(metadata) = 'object')
            );

            CREATE INDEX ix_menu_audit_created_at
                ON menu.audit_log (created_at DESC);
            CREATE INDEX ix_menu_audit_entity_created
                ON menu.audit_log (entity_type ASC, entity_key ASC, created_at DESC);
            CREATE INDEX ix_menu_audit_actor_created
                ON menu.audit_log (actor_id ASC, created_at DESC);
            CREATE INDEX ix_menu_audit_release
                ON menu.audit_log (release_id);
            CREATE INDEX ix_menu_audit_revision
                ON menu.audit_log (revision_id);

            CREATE TABLE menu.server_status (
                server_key VARCHAR(64) NOT NULL,
                runtime_session_id UUID NOT NULL,
                generation BIGINT NOT NULL DEFAULT 1,
                menu_core_version VARCHAR(32) NOT NULL,
                swiftly_version VARCHAR(64) NOT NULL,
                menu_api_version INTEGER NOT NULL,
                schema_version INTEGER NOT NULL,
                capabilities JSONB NOT NULL DEFAULT '{}'::jsonb,
                active_release_id BIGINT NULL,
                active_checksum CHARACTER(64) NULL,
                loaded_source VARCHAR(32) NULL,
                last_db_sync_at TIMESTAMPTZ NULL,
                lkg_release_id BIGINT NULL,
                fallback_release_id BIGINT NULL,
                validation_status VARCHAR(32) NOT NULL DEFAULT 'not_loaded',
                last_error TEXT NULL,
                heartbeat_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT pk_menu_server_status PRIMARY KEY (server_key),
                CONSTRAINT ck_menu_server_status_key
                    CHECK (server_key ~ '^[A-Za-z0-9][A-Za-z0-9_.-]{0,63}$'),
                CONSTRAINT ck_menu_server_status_generation CHECK (generation > 0),
                CONSTRAINT ck_menu_server_status_menu_api CHECK (menu_api_version > 0),
                CONSTRAINT ck_menu_server_status_schema CHECK (schema_version > 0),
                CONSTRAINT ck_menu_server_status_capabilities
                    CHECK (jsonb_typeof(capabilities) = 'object'),
                CONSTRAINT ck_menu_server_status_source
                    CHECK (loaded_source IS NULL OR loaded_source IN ('database','lkg','fallback')),
                CONSTRAINT ck_menu_server_status_validation
                    CHECK (validation_status IN ('not_loaded','valid','invalid','degraded')),
                CONSTRAINT ck_menu_server_status_active_checksum
                    CHECK (active_checksum IS NULL OR active_checksum ~ '^[0-9a-f]{64}$')
            );

            CREATE INDEX ix_menu_server_status_session
                ON menu.server_status (runtime_session_id);
            CREATE INDEX ix_menu_server_status_heartbeat
                ON menu.server_status (heartbeat_at);

            CREATE FUNCTION menu.prevent_immutable_change()
            RETURNS TRIGGER
            LANGUAGE plpgsql
            AS $$
            BEGIN
                RAISE EXCEPTION 'menu.% is immutable after publication', TG_TABLE_NAME
                    USING ERRCODE = '55000';
            END;
            $$;

            CREATE TRIGGER menu_revisions_immutable
                BEFORE UPDATE OR DELETE ON menu.revisions
                FOR EACH ROW EXECUTE FUNCTION menu.prevent_immutable_change();
            CREATE TRIGGER menu_releases_immutable
                BEFORE UPDATE OR DELETE ON menu.releases
                FOR EACH ROW EXECUTE FUNCTION menu.prevent_immutable_change();
            CREATE TRIGGER menu_release_items_immutable
                BEFORE UPDATE OR DELETE ON menu.release_items
                FOR EACH ROW EXECUTE FUNCTION menu.prevent_immutable_change();
            CREATE TRIGGER menu_release_targets_immutable
                BEFORE UPDATE OR DELETE ON menu.release_targets
                FOR EACH ROW EXECUTE FUNCTION menu.prevent_immutable_change();
            CREATE TRIGGER menu_commands_immutable
                BEFORE UPDATE OR DELETE ON menu.commands
                FOR EACH ROW EXECUTE FUNCTION menu.prevent_immutable_change();
            CREATE TRIGGER menu_audit_append_only
                BEFORE UPDATE OR DELETE ON menu.audit_log
                FOR EACH ROW EXECUTE FUNCTION menu.prevent_immutable_change();
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            DROP TABLE IF EXISTS menu.audit_log;
            DROP TABLE IF EXISTS menu.commands;
            DROP TABLE IF EXISTS menu.release_heads;
            DROP TABLE IF EXISTS menu.release_targets;
            DROP TABLE IF EXISTS menu.release_items;
            DROP TABLE IF EXISTS menu.drafts;
            DROP TABLE IF EXISTS menu.releases;
            DROP TABLE IF EXISTS menu.revisions;
            DROP TABLE IF EXISTS menu.definitions;
            DROP TABLE IF EXISTS menu.provider_exports;
            DROP TABLE IF EXISTS menu.provider_instances;
            DROP TABLE IF EXISTS menu.providers;
            DROP TABLE IF EXISTS menu.server_status;
            DROP FUNCTION IF EXISTS menu.prevent_immutable_change();
            """);
    }
}
