// <auto-generated />
using Menu.Core.Database.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Menu.Core.Database.Migrations;

[DbContext(typeof(MenuDbContext))]
internal sealed class MenuDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema(MenuDbContext.SchemaName)
            .HasAnnotation("ProductVersion", "9.0.3")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        ConfigureProviders(modelBuilder);
        ConfigureDefinitions(modelBuilder);
        ConfigureReleases(modelBuilder);
        ConfigureOperations(modelBuilder);
#pragma warning restore 612, 618
    }

    // Snapshot намеренно дублирует зафиксированную модель вместо загрузки текущих
    // IEntityTypeConfiguration, чтобы последующие изменения образовывали diff.
    private static void ConfigureProviders(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<MenuProviderEntity>(builder =>
        {
            builder.ToTable("providers", MenuDbContext.SchemaName, table =>
            {
                table.HasCheckConstraint("ck_menu_providers_key", "provider_key ~ '^[a-z0-9][a-z0-9_.-]{0,127}$'");
                table.HasCheckConstraint("ck_menu_providers_metadata", "jsonb_typeof(metadata) = 'object'");
            });
            builder.HasKey(x => x.Id).HasName("pk_menu_providers");
            builder.Property(x => x.Id).HasColumnName("id");
            builder.Property(x => x.ProviderKey).HasColumnName("provider_key").HasMaxLength(128).IsRequired();
            builder.Property(x => x.DisplayName).HasColumnName("display_name").HasMaxLength(128).IsRequired();
            builder.Property(x => x.MetadataJson).HasColumnName("metadata").HasColumnType("jsonb").HasDefaultValueSql("'{}'::jsonb").IsRequired();
            builder.Property(x => x.CreatedAt).HasColumnName("created_at").HasDefaultValueSql("CURRENT_TIMESTAMP");
            builder.Property(x => x.UpdatedAt).HasColumnName("updated_at").HasDefaultValueSql("CURRENT_TIMESTAMP");
            builder.HasIndex(x => x.ProviderKey).IsUnique().HasDatabaseName("ux_menu_providers_key");
            builder.HasIndex(x => x.UpdatedAt).HasDatabaseName("ix_menu_providers_updated_at");
        });

        modelBuilder.Entity<MenuProviderInstanceEntity>(builder =>
        {
            builder.ToTable("provider_instances", MenuDbContext.SchemaName, table =>
            {
                table.HasCheckConstraint("ck_menu_provider_instances_server_key", "server_key ~ '^[A-Za-z0-9][A-Za-z0-9_.-]{0,63}$'");
                table.HasCheckConstraint("ck_menu_provider_instances_status", "status IN ('online','offline','incompatible','api_outdated','error')");
                table.HasCheckConstraint("ck_menu_provider_instances_api_version", "menu_api_version > 0");
                table.HasCheckConstraint("ck_menu_provider_instances_generation", "generation > 0");
                table.HasCheckConstraint("ck_menu_provider_instances_capabilities", "jsonb_typeof(capabilities) = 'array'");
                table.HasCheckConstraint("ck_menu_provider_instances_metadata", "jsonb_typeof(metadata) = 'object'");
            });
            builder.HasKey(x => x.Id).HasName("pk_menu_provider_instances");
            builder.Property(x => x.Id).HasColumnName("id");
            builder.Property(x => x.ProviderId).HasColumnName("provider_id");
            builder.Property(x => x.ServerKey).HasColumnName("server_key").HasMaxLength(64).IsRequired();
            builder.Property(x => x.PluginVersion).HasColumnName("plugin_version").HasMaxLength(32).IsRequired();
            builder.Property(x => x.MenuApiVersion).HasColumnName("menu_api_version");
            builder.Property(x => x.Status).HasColumnName("status").HasMaxLength(32).HasDefaultValue("offline").IsRequired();
            builder.Property(x => x.CapabilitiesJson).HasColumnName("capabilities").HasColumnType("jsonb").HasDefaultValueSql("'[]'::jsonb").IsRequired();
            builder.Property(x => x.MetadataJson).HasColumnName("metadata").HasColumnType("jsonb").HasDefaultValueSql("'{}'::jsonb").IsRequired();
            builder.Property(x => x.SessionId).HasColumnName("session_id");
            builder.Property(x => x.Generation).HasColumnName("generation").HasDefaultValue(1L);
            builder.Property(x => x.RegisteredAt).HasColumnName("registered_at").HasDefaultValueSql("CURRENT_TIMESTAMP");
            builder.Property(x => x.LastSeenAt).HasColumnName("last_seen_at").HasDefaultValueSql("CURRENT_TIMESTAMP");
            builder.Property(x => x.OfflineAt).HasColumnName("offline_at");
            builder.Property(x => x.UpdatedAt).HasColumnName("updated_at").HasDefaultValueSql("CURRENT_TIMESTAMP");
            builder.Property(x => x.LastError).HasColumnName("last_error");
            builder.HasIndex(x => new { x.ProviderId, x.ServerKey }).IsUnique().HasDatabaseName("ux_menu_provider_instances_provider_server");
            builder.HasIndex(x => x.SessionId).HasDatabaseName("ix_menu_provider_instances_session");
            builder.HasIndex(x => new { x.ServerKey, x.Status, x.LastSeenAt }).HasDatabaseName("ix_menu_provider_instances_server_status_seen");
            builder.HasOne(x => x.Provider).WithMany(x => x.Instances).HasForeignKey(x => x.ProviderId)
                .HasConstraintName("fk_menu_provider_instances_provider").OnDelete(DeleteBehavior.Restrict);
        });

        modelBuilder.Entity<MenuProviderExportEntity>(builder =>
        {
            builder.ToTable("provider_exports", MenuDbContext.SchemaName, table =>
            {
                table.HasCheckConstraint("ck_menu_provider_exports_type", "export_type IN ('menu','action')");
                table.HasCheckConstraint("ck_menu_provider_exports_key", "export_key ~ '^[a-z0-9][a-z0-9_.-]{0,127}$'");
                table.HasCheckConstraint("ck_menu_provider_exports_generation", "declared_generation > 0");
                table.HasCheckConstraint("ck_menu_provider_exports_schema", "schema IS NULL OR jsonb_typeof(schema) = 'object'");
                table.HasCheckConstraint("ck_menu_provider_exports_metadata", "jsonb_typeof(metadata) = 'object'");
            });
            builder.HasKey(x => x.Id).HasName("pk_menu_provider_exports");
            builder.Property(x => x.Id).HasColumnName("id");
            builder.Property(x => x.ProviderInstanceId).HasColumnName("provider_instance_id");
            builder.Property(x => x.ExportType).HasColumnName("export_type").HasMaxLength(16).IsRequired();
            builder.Property(x => x.ExportKey).HasColumnName("export_key").HasMaxLength(128).IsRequired();
            builder.Property(x => x.DisplayName).HasColumnName("display_name").HasMaxLength(128).IsRequired();
            builder.Property(x => x.SchemaJson).HasColumnName("schema").HasColumnType("jsonb");
            builder.Property(x => x.MetadataJson).HasColumnName("metadata").HasColumnType("jsonb").HasDefaultValueSql("'{}'::jsonb").IsRequired();
            builder.Property(x => x.IsDeclared).HasColumnName("is_declared").HasDefaultValue(true);
            builder.Property(x => x.DeclaredGeneration).HasColumnName("declared_generation");
            builder.Property(x => x.FirstSeenAt).HasColumnName("first_seen_at").HasDefaultValueSql("CURRENT_TIMESTAMP");
            builder.Property(x => x.LastSeenAt).HasColumnName("last_seen_at").HasDefaultValueSql("CURRENT_TIMESTAMP");
            builder.Property(x => x.UpdatedAt).HasColumnName("updated_at").HasDefaultValueSql("CURRENT_TIMESTAMP");
            builder.HasIndex(x => new { x.ProviderInstanceId, x.ExportType, x.ExportKey }).IsUnique().HasDatabaseName("ux_menu_provider_exports_instance_type_key");
            builder.HasIndex(x => new { x.ProviderInstanceId, x.IsDeclared }).HasDatabaseName("ix_menu_provider_exports_declared");
            builder.HasOne(x => x.ProviderInstance).WithMany(x => x.Exports).HasForeignKey(x => x.ProviderInstanceId)
                .HasConstraintName("fk_menu_provider_exports_instance").OnDelete(DeleteBehavior.Restrict);
        });
    }

    private static void ConfigureDefinitions(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<MenuDefinitionEntity>(builder =>
        {
            builder.ToTable("definitions", MenuDbContext.SchemaName, table =>
            {
                table.HasCheckConstraint("ck_menu_definitions_key", "menu_key ~ '^[a-z0-9][a-z0-9_.-]{0,127}$'");
                table.HasCheckConstraint("ck_menu_definitions_owner_provider", "owner_provider_key IS NULL OR owner_provider_key ~ '^[a-z0-9][a-z0-9_.-]{0,127}$'");
                table.HasCheckConstraint("ck_menu_definitions_status", "status IN ('draft','published','archived')");
            });
            builder.HasKey(x => x.Id).HasName("pk_menu_definitions");
            builder.Property(x => x.Id).HasColumnName("id");
            builder.Property(x => x.MenuKey).HasColumnName("menu_key").HasMaxLength(128).IsRequired();
            builder.Property(x => x.Title).HasColumnName("title").HasMaxLength(128).IsRequired();
            builder.Property(x => x.Description).HasColumnName("description");
            builder.Property(x => x.OwnerProviderKey).HasColumnName("owner_provider_key").HasMaxLength(128);
            builder.Property(x => x.Status).HasColumnName("status").HasMaxLength(16).HasDefaultValue("draft").IsRequired();
            builder.Property(x => x.CreatedBy).HasColumnName("created_by").HasMaxLength(128);
            builder.Property(x => x.UpdatedBy).HasColumnName("updated_by").HasMaxLength(128);
            builder.Property(x => x.CreatedAt).HasColumnName("created_at").HasDefaultValueSql("CURRENT_TIMESTAMP");
            builder.Property(x => x.UpdatedAt).HasColumnName("updated_at").HasDefaultValueSql("CURRENT_TIMESTAMP");
            builder.HasIndex(x => x.MenuKey).IsUnique().HasDatabaseName("ux_menu_definitions_key");
            builder.HasIndex(x => new { x.Status, x.UpdatedAt }).HasDatabaseName("ix_menu_definitions_status_updated");
        });

        modelBuilder.Entity<MenuRevisionEntity>(builder =>
        {
            builder.ToTable("revisions", MenuDbContext.SchemaName, table =>
            {
                table.HasCheckConstraint("ck_menu_revisions_number", "revision_number > 0");
                table.HasCheckConstraint("ck_menu_revisions_schema_version", "schema_version > 0");
                table.HasCheckConstraint("ck_menu_revisions_payload", "jsonb_typeof(payload) = 'object'");
                table.HasCheckConstraint("ck_menu_revisions_checksum", "checksum ~ '^[0-9a-f]{64}$'");
            });
            builder.HasKey(x => x.Id).HasName("pk_menu_revisions");
            builder.HasAlternateKey(x => new { x.Id, x.DefinitionId }).HasName("ak_menu_revisions_id_definition");
            builder.Property(x => x.Id).HasColumnName("id");
            builder.Property(x => x.DefinitionId).HasColumnName("definition_id");
            builder.Property(x => x.RevisionNumber).HasColumnName("revision_number");
            builder.Property(x => x.SchemaVersion).HasColumnName("schema_version");
            builder.Property(x => x.PayloadJson).HasColumnName("payload").HasColumnType("jsonb").IsRequired();
            builder.Property(x => x.Checksum).HasColumnName("checksum").HasColumnType("character(64)").IsRequired();
            builder.Property(x => x.BasedOnRevisionId).HasColumnName("based_on_revision_id");
            builder.Property(x => x.CreatedBy).HasColumnName("created_by").HasMaxLength(128);
            builder.Property(x => x.CreatedAt).HasColumnName("created_at").HasDefaultValueSql("CURRENT_TIMESTAMP");
            builder.Property(x => x.PublishedAt).HasColumnName("published_at").HasDefaultValueSql("CURRENT_TIMESTAMP");
            builder.HasIndex(x => new { x.DefinitionId, x.RevisionNumber }).IsUnique().HasDatabaseName("ux_menu_revisions_definition_number");
            builder.HasIndex(x => new { x.DefinitionId, x.PublishedAt }).IsDescending(false, true).HasDatabaseName("ix_menu_revisions_definition_published");
            builder.HasIndex(x => new { x.BasedOnRevisionId, x.DefinitionId }).HasDatabaseName("ix_menu_revisions_based_on");
            builder.HasOne(x => x.Definition).WithMany(x => x.Revisions).HasForeignKey(x => x.DefinitionId)
                .HasConstraintName("fk_menu_revisions_definition").OnDelete(DeleteBehavior.Restrict);
            builder.HasOne(x => x.BasedOnRevision).WithMany(x => x.DerivedRevisions)
                .HasForeignKey(x => new { x.BasedOnRevisionId, x.DefinitionId })
                .HasPrincipalKey(x => new { x.Id, x.DefinitionId })
                .HasConstraintName("fk_menu_revisions_based_on").OnDelete(DeleteBehavior.Restrict);
        });

        modelBuilder.Entity<MenuDraftEntity>(builder =>
        {
            builder.ToTable("drafts", MenuDbContext.SchemaName, table =>
            {
                table.HasCheckConstraint("ck_menu_drafts_schema_version", "schema_version > 0");
                table.HasCheckConstraint("ck_menu_drafts_payload", "jsonb_typeof(payload) = 'object'");
                table.HasCheckConstraint("ck_menu_drafts_lock_version", "lock_version >= 0");
            });
            builder.HasKey(x => x.Id).HasName("pk_menu_drafts");
            builder.Property(x => x.Id).HasColumnName("id");
            builder.Property(x => x.DefinitionId).HasColumnName("definition_id");
            builder.Property(x => x.BaseRevisionId).HasColumnName("base_revision_id");
            builder.Property(x => x.SchemaVersion).HasColumnName("schema_version");
            builder.Property(x => x.PayloadJson).HasColumnName("payload").HasColumnType("jsonb").IsRequired();
            builder.Property(x => x.LockVersion).HasColumnName("lock_version").HasDefaultValue(0L).IsConcurrencyToken();
            builder.Property(x => x.CreatedBy).HasColumnName("created_by").HasMaxLength(128);
            builder.Property(x => x.UpdatedBy).HasColumnName("updated_by").HasMaxLength(128);
            builder.Property(x => x.CreatedAt).HasColumnName("created_at").HasDefaultValueSql("CURRENT_TIMESTAMP");
            builder.Property(x => x.UpdatedAt).HasColumnName("updated_at").HasDefaultValueSql("CURRENT_TIMESTAMP");
            builder.HasIndex(x => x.DefinitionId).IsUnique().HasDatabaseName("ux_menu_drafts_definition");
            builder.HasIndex(x => x.UpdatedAt).HasDatabaseName("ix_menu_drafts_updated_at");
            builder.HasIndex(x => new { x.BaseRevisionId, x.DefinitionId }).HasDatabaseName("ix_menu_drafts_base_revision");
            builder.HasOne(x => x.Definition).WithOne(x => x.Draft).HasForeignKey<MenuDraftEntity>(x => x.DefinitionId)
                .HasConstraintName("fk_menu_drafts_definition").OnDelete(DeleteBehavior.Cascade);
            builder.HasOne(x => x.BaseRevision).WithMany().HasForeignKey(x => new { x.BaseRevisionId, x.DefinitionId })
                .HasPrincipalKey(x => new { x.Id, x.DefinitionId })
                .HasConstraintName("fk_menu_drafts_base_revision").OnDelete(DeleteBehavior.Restrict);
        });
    }

    private static void ConfigureReleases(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<MenuReleaseEntity>(builder =>
        {
            builder.ToTable("releases", MenuDbContext.SchemaName, table =>
            {
                table.HasCheckConstraint("ck_menu_releases_number", "release_number > 0");
                table.HasCheckConstraint("ck_menu_releases_schema_version", "schema_version > 0");
                table.HasCheckConstraint("ck_menu_releases_api_version", "menu_core_api_version > 0");
            });
            builder.HasKey(x => x.Id).HasName("pk_menu_releases");
            builder.Property(x => x.Id).HasColumnName("id");
            builder.Property(x => x.ReleaseNumber).HasColumnName("release_number");
            builder.Property(x => x.SchemaVersion).HasColumnName("schema_version");
            builder.Property(x => x.MenuCoreApiVersion).HasColumnName("menu_core_api_version");
            builder.Property(x => x.RollbackOfReleaseId).HasColumnName("rollback_of_release_id");
            builder.Property(x => x.CreatedBy).HasColumnName("created_by").HasMaxLength(128);
            builder.Property(x => x.CreatedAt).HasColumnName("created_at").HasDefaultValueSql("CURRENT_TIMESTAMP");
            builder.Property(x => x.PublishedAt).HasColumnName("published_at").HasDefaultValueSql("CURRENT_TIMESTAMP");
            builder.HasIndex(x => x.ReleaseNumber).IsUnique().HasDatabaseName("ux_menu_releases_number");
            builder.HasIndex(x => x.PublishedAt).IsDescending().HasDatabaseName("ix_menu_releases_published_at");
            builder.HasIndex(x => x.RollbackOfReleaseId).HasDatabaseName("ix_menu_releases_rollback_of");
            builder.HasOne(x => x.RollbackOfRelease).WithMany(x => x.RollbackReleases)
                .HasForeignKey(x => x.RollbackOfReleaseId)
                .HasConstraintName("fk_menu_releases_rollback_of").OnDelete(DeleteBehavior.Restrict);
        });

        modelBuilder.Entity<MenuReleaseItemEntity>(builder =>
        {
            builder.ToTable("release_items", MenuDbContext.SchemaName);
            builder.HasKey(x => new { x.ReleaseId, x.DefinitionId }).HasName("pk_menu_release_items");
            builder.HasAlternateKey(x => new { x.ReleaseId, x.RevisionId }).HasName("ak_menu_release_items_release_revision");
            builder.Property(x => x.ReleaseId).HasColumnName("release_id");
            builder.Property(x => x.DefinitionId).HasColumnName("definition_id");
            builder.Property(x => x.RevisionId).HasColumnName("revision_id");
            builder.HasIndex(x => x.DefinitionId).HasDatabaseName("ix_menu_release_items_definition");
            builder.HasIndex(x => new { x.RevisionId, x.DefinitionId }).HasDatabaseName("ix_menu_release_items_revision");
            builder.HasOne(x => x.Release).WithMany(x => x.Items).HasForeignKey(x => x.ReleaseId)
                .HasConstraintName("fk_menu_release_items_release").OnDelete(DeleteBehavior.Restrict);
            builder.HasOne(x => x.Definition).WithMany(x => x.ReleaseItems).HasForeignKey(x => x.DefinitionId)
                .HasConstraintName("fk_menu_release_items_definition").OnDelete(DeleteBehavior.Restrict);
            builder.HasOne(x => x.Revision).WithMany(x => x.ReleaseItems)
                .HasForeignKey(x => new { x.RevisionId, x.DefinitionId })
                .HasPrincipalKey(x => new { x.Id, x.DefinitionId })
                .HasConstraintName("fk_menu_release_items_revision").OnDelete(DeleteBehavior.Restrict);
        });

        modelBuilder.Entity<MenuReleaseTargetEntity>(builder =>
        {
            builder.ToTable("release_targets", MenuDbContext.SchemaName, table =>
            {
                table.HasCheckConstraint("ck_menu_release_targets_server", "server_key ~ '^[A-Za-z0-9][A-Za-z0-9_.-]{0,63}$'");
                table.HasCheckConstraint("ck_menu_release_targets_server_group", "server_group_key IS NULL OR server_group_key ~ '^[A-Za-z0-9][A-Za-z0-9_.-]{0,63}$'");
                table.HasCheckConstraint("ck_menu_release_targets_artifact", "jsonb_typeof(artifact_json::jsonb) = 'object'");
                table.HasCheckConstraint("ck_menu_release_targets_checksum", "checksum ~ '^[0-9a-f]{64}$'");
                table.HasCheckConstraint("ck_menu_release_targets_capabilities", "jsonb_typeof(capability_manifest) = 'object'");
            });
            builder.HasKey(x => new { x.ReleaseId, x.ServerKey }).HasName("pk_menu_release_targets");
            builder.Property(x => x.ReleaseId).HasColumnName("release_id");
            builder.Property(x => x.ServerKey).HasColumnName("server_key").HasMaxLength(64);
            builder.Property(x => x.ServerGroupKey).HasColumnName("server_group_key").HasMaxLength(64);
            builder.Property(x => x.ArtifactJson).HasColumnName("artifact_json").HasColumnType("text").IsRequired();
            builder.Property(x => x.Checksum).HasColumnName("checksum").HasColumnType("character(64)").IsRequired();
            builder.Property(x => x.CapabilityManifestJson).HasColumnName("capability_manifest").HasColumnType("jsonb").HasDefaultValueSql("'{}'::jsonb").IsRequired();
            builder.Property(x => x.CreatedAt).HasColumnName("created_at").HasDefaultValueSql("CURRENT_TIMESTAMP");
            builder.HasIndex(x => new { x.ServerKey, x.ReleaseId }).HasDatabaseName("ix_menu_release_targets_server_release");
            builder.HasIndex(x => x.Checksum).HasDatabaseName("ix_menu_release_targets_checksum");
            builder.HasOne(x => x.Release).WithMany(x => x.Targets).HasForeignKey(x => x.ReleaseId)
                .HasConstraintName("fk_menu_release_targets_release").OnDelete(DeleteBehavior.Restrict);
        });

        modelBuilder.Entity<MenuReleaseHeadEntity>(builder =>
        {
            builder.ToTable("release_heads", MenuDbContext.SchemaName, table =>
            {
                table.HasCheckConstraint("ck_menu_release_heads_server", "server_key ~ '^[A-Za-z0-9][A-Za-z0-9_.-]{0,63}$'");
                table.HasCheckConstraint("ck_menu_release_heads_lock_version", "lock_version >= 0");
            });
            builder.HasKey(x => x.ServerKey).HasName("pk_menu_release_heads");
            builder.Property(x => x.ServerKey).HasColumnName("server_key").HasMaxLength(64);
            builder.Property(x => x.ReleaseId).HasColumnName("release_id");
            builder.Property(x => x.LockVersion).HasColumnName("lock_version").HasDefaultValue(0L).IsConcurrencyToken();
            builder.Property(x => x.UpdatedBy).HasColumnName("updated_by").HasMaxLength(128);
            builder.Property(x => x.UpdatedAt).HasColumnName("updated_at").HasDefaultValueSql("CURRENT_TIMESTAMP");
            builder.HasIndex(x => new { x.ReleaseId, x.ServerKey }).HasDatabaseName("ix_menu_release_heads_release");
            builder.HasOne(x => x.Target).WithOne(x => x.Head)
                .HasForeignKey<MenuReleaseHeadEntity>(x => new { x.ReleaseId, x.ServerKey })
                .HasPrincipalKey<MenuReleaseTargetEntity>(x => new { x.ReleaseId, x.ServerKey })
                .HasConstraintName("fk_menu_release_heads_target").OnDelete(DeleteBehavior.Restrict);
        });

        modelBuilder.Entity<MenuCommandEntity>(builder =>
        {
            builder.ToTable("commands", MenuDbContext.SchemaName, table =>
            {
                table.HasCheckConstraint("ck_menu_commands_server", "server_key ~ '^[A-Za-z0-9][A-Za-z0-9_.-]{0,63}$'");
                table.HasCheckConstraint("ck_menu_commands_menu_key", "menu_key ~ '^[a-z0-9][a-z0-9_.-]{0,127}$'");
                table.HasCheckConstraint("ck_menu_commands_type", "command_type IN ('chat','console')");
                table.HasCheckConstraint("ck_menu_commands_alias", "btrim(alias) <> '' AND btrim(normalized_alias) <> ''");
                table.HasCheckConstraint("ck_menu_commands_suppression", "suppression_mode IN ('none','on_match','on_success')");
            });
            builder.HasKey(x => x.Id).HasName("pk_menu_commands");
            builder.Property(x => x.Id).HasColumnName("id");
            builder.Property(x => x.ReleaseId).HasColumnName("release_id");
            builder.Property(x => x.ServerKey).HasColumnName("server_key").HasMaxLength(64);
            builder.Property(x => x.RevisionId).HasColumnName("revision_id");
            builder.Property(x => x.MenuKey).HasColumnName("menu_key").HasMaxLength(128);
            builder.Property(x => x.CommandType).HasColumnName("command_type").HasMaxLength(16);
            builder.Property(x => x.Alias).HasColumnName("alias").HasMaxLength(128);
            builder.Property(x => x.NormalizedAlias).HasColumnName("normalized_alias").HasMaxLength(128);
            builder.Property(x => x.SuppressionMode).HasColumnName("suppression_mode").HasMaxLength(16).HasDefaultValue("none");
            builder.Property(x => x.Enabled).HasColumnName("enabled").HasDefaultValue(true);
            builder.Property(x => x.CreatedAt).HasColumnName("created_at").HasDefaultValueSql("CURRENT_TIMESTAMP");
            builder.HasIndex(x => new { x.ReleaseId, x.ServerKey, x.CommandType, x.NormalizedAlias }).IsUnique()
                .HasFilter("enabled = TRUE").HasDatabaseName("ux_menu_commands_active_route");
            builder.HasIndex(x => x.RevisionId).HasDatabaseName("ix_menu_commands_revision");
            builder.HasIndex(x => new { x.ReleaseId, x.ServerKey }).HasDatabaseName("ix_menu_commands_target");
            builder.HasIndex(x => new { x.ReleaseId, x.RevisionId }).HasDatabaseName("ix_menu_commands_release_item");
            builder.HasIndex(x => new { x.ServerKey, x.CommandType, x.NormalizedAlias })
                .HasFilter("enabled = TRUE").HasDatabaseName("ix_menu_commands_server_lookup");
            builder.HasOne(x => x.ReleaseTarget).WithMany(x => x.Commands)
                .HasForeignKey(x => new { x.ReleaseId, x.ServerKey })
                .HasConstraintName("fk_menu_commands_target").OnDelete(DeleteBehavior.Restrict);
            builder.HasOne(x => x.ReleaseItem).WithMany(x => x.Commands)
                .HasForeignKey(x => new { x.ReleaseId, x.RevisionId })
                .HasPrincipalKey(x => new { x.ReleaseId, x.RevisionId })
                .HasConstraintName("fk_menu_commands_release_item").OnDelete(DeleteBehavior.Restrict);
        });
    }

    private static void ConfigureOperations(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<MenuAuditLogEntity>(builder =>
        {
            builder.ToTable("audit_log", MenuDbContext.SchemaName, table =>
            {
                table.HasCheckConstraint("ck_menu_audit_action", "btrim(action) <> ''");
                table.HasCheckConstraint("ck_menu_audit_entity_type", "btrim(entity_type) <> ''");
                table.HasCheckConstraint("ck_menu_audit_changes", "jsonb_typeof(changes) = 'object'");
                table.HasCheckConstraint("ck_menu_audit_metadata", "jsonb_typeof(metadata) = 'object'");
            });
            builder.HasKey(x => x.Id).HasName("pk_menu_audit_log");
            builder.Property(x => x.Id).HasColumnName("id");
            builder.Property(x => x.ActorId).HasColumnName("actor_id").HasMaxLength(128);
            builder.Property(x => x.ActorDisplayName).HasColumnName("actor_display_name").HasMaxLength(128);
            builder.Property(x => x.Action).HasColumnName("action").HasMaxLength(64).IsRequired();
            builder.Property(x => x.EntityType).HasColumnName("entity_type").HasMaxLength(32).IsRequired();
            builder.Property(x => x.EntityKey).HasColumnName("entity_key").HasMaxLength(128);
            builder.Property(x => x.ServerKey).HasColumnName("server_key").HasMaxLength(64);
            builder.Property(x => x.ReleaseId).HasColumnName("release_id");
            builder.Property(x => x.RevisionId).HasColumnName("revision_id");
            builder.Property(x => x.ChangesJson).HasColumnName("changes").HasColumnType("jsonb").HasDefaultValueSql("'{}'::jsonb").IsRequired();
            builder.Property(x => x.MetadataJson).HasColumnName("metadata").HasColumnType("jsonb").HasDefaultValueSql("'{}'::jsonb").IsRequired();
            builder.Property(x => x.CreatedAt).HasColumnName("created_at").HasDefaultValueSql("CURRENT_TIMESTAMP");
            builder.HasIndex(x => x.CreatedAt).IsDescending().HasDatabaseName("ix_menu_audit_created_at");
            builder.HasIndex(x => new { x.EntityType, x.EntityKey, x.CreatedAt }).IsDescending(false, false, true).HasDatabaseName("ix_menu_audit_entity_created");
            builder.HasIndex(x => new { x.ActorId, x.CreatedAt }).IsDescending(false, true).HasDatabaseName("ix_menu_audit_actor_created");
            builder.HasIndex(x => x.ReleaseId).HasDatabaseName("ix_menu_audit_release");
            builder.HasIndex(x => x.RevisionId).HasDatabaseName("ix_menu_audit_revision");
            builder.HasOne(x => x.Release).WithMany().HasForeignKey(x => x.ReleaseId)
                .HasConstraintName("fk_menu_audit_release").OnDelete(DeleteBehavior.Restrict);
            builder.HasOne(x => x.Revision).WithMany().HasForeignKey(x => x.RevisionId)
                .HasConstraintName("fk_menu_audit_revision").OnDelete(DeleteBehavior.Restrict);
        });

        modelBuilder.Entity<MenuServerStatusEntity>(builder =>
        {
            builder.ToTable("server_status", MenuDbContext.SchemaName, table =>
            {
                table.HasCheckConstraint("ck_menu_server_status_key", "server_key ~ '^[A-Za-z0-9][A-Za-z0-9_.-]{0,63}$'");
                table.HasCheckConstraint("ck_menu_server_status_generation", "generation > 0");
                table.HasCheckConstraint("ck_menu_server_status_menu_api", "menu_api_version > 0");
                table.HasCheckConstraint("ck_menu_server_status_schema", "schema_version > 0");
                table.HasCheckConstraint("ck_menu_server_status_capabilities", "jsonb_typeof(capabilities) = 'object'");
                table.HasCheckConstraint("ck_menu_server_status_source", "loaded_source IS NULL OR loaded_source IN ('database','lkg','fallback')");
                table.HasCheckConstraint("ck_menu_server_status_validation", "validation_status IN ('not_loaded','valid','invalid','degraded')");
                table.HasCheckConstraint("ck_menu_server_status_active_checksum", "active_checksum IS NULL OR active_checksum ~ '^[0-9a-f]{64}$'");
            });
            builder.HasKey(x => x.ServerKey).HasName("pk_menu_server_status");
            builder.Property(x => x.ServerKey).HasColumnName("server_key").HasMaxLength(64);
            builder.Property(x => x.RuntimeSessionId).HasColumnName("runtime_session_id");
            builder.Property(x => x.Generation).HasColumnName("generation").HasDefaultValue(1L);
            builder.Property(x => x.MenuCoreVersion).HasColumnName("menu_core_version").HasMaxLength(32);
            builder.Property(x => x.SwiftlyVersion).HasColumnName("swiftly_version").HasMaxLength(64);
            builder.Property(x => x.MenuApiVersion).HasColumnName("menu_api_version");
            builder.Property(x => x.SchemaVersion).HasColumnName("schema_version");
            builder.Property(x => x.CapabilitiesJson).HasColumnName("capabilities").HasColumnType("jsonb").HasDefaultValueSql("'{}'::jsonb").IsRequired();
            builder.Property(x => x.ActiveReleaseId).HasColumnName("active_release_id");
            builder.Property(x => x.ActiveChecksum).HasColumnName("active_checksum").HasColumnType("character(64)");
            builder.Property(x => x.LoadedSource).HasColumnName("loaded_source").HasMaxLength(32);
            builder.Property(x => x.LastDbSyncAt).HasColumnName("last_db_sync_at");
            builder.Property(x => x.LastKnownGoodReleaseId).HasColumnName("lkg_release_id");
            builder.Property(x => x.FallbackReleaseId).HasColumnName("fallback_release_id");
            builder.Property(x => x.ValidationStatus).HasColumnName("validation_status").HasMaxLength(32).HasDefaultValue("not_loaded");
            builder.Property(x => x.LastError).HasColumnName("last_error");
            builder.Property(x => x.HeartbeatAt).HasColumnName("heartbeat_at").HasDefaultValueSql("CURRENT_TIMESTAMP");
            builder.Property(x => x.UpdatedAt).HasColumnName("updated_at").HasDefaultValueSql("CURRENT_TIMESTAMP");
            builder.HasIndex(x => x.RuntimeSessionId).HasDatabaseName("ix_menu_server_status_session");
            builder.HasIndex(x => x.HeartbeatAt).HasDatabaseName("ix_menu_server_status_heartbeat");
        });
    }
}
