// <auto-generated />
using System;
using MapRotation.Core.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MapRotation.Core.Database.Migrations
{
    [DbContext(typeof(MapRotationDbContext))]
    [Migration("20260925120000_AddMapRotationCompactHud")]
    partial class AddMapRotationCompactHud
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("map_rotation")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MapRotation.Core.Database.HistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<long?>("MapId")
                        .HasColumnType("bigint")
                        .HasColumnName("map_id");

                    b.Property<string>("MapName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("map_name");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("WorkshopId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("workshop_id");

                    b.HasKey("Id");

                    b.HasIndex("EndedAt");

                    b.ToTable("map_history", "map_rotation");
                });

            modelBuilder.Entity("MapRotation.Core.Database.RotationHudPreferenceEntity", b =>
                {
                    b.Property<long>("SteamId").HasColumnType("bigint").HasColumnName("steam_id");
                    b.Property<string>("Orientation").IsRequired().ValueGeneratedOnAdd().HasMaxLength(10)
                        .HasColumnType("character varying(10)").HasDefaultValue("horizontal").HasColumnName("orientation");
                    b.Property<int>("HudScale").ValueGeneratedOnAdd().HasColumnType("integer")
                        .HasDefaultValue(80).HasColumnName("hud_scale");
                    b.Property<string>("DockSide").IsRequired().ValueGeneratedOnAdd().HasMaxLength(5)
                        .HasColumnType("character varying(5)").HasDefaultValue("right").HasColumnName("dock_side");
                    b.Property<string>("Animation").IsRequired().ValueGeneratedOnAdd().HasMaxLength(6)
                        .HasColumnType("character varying(6)").HasDefaultValue("normal").HasColumnName("animation");
                    b.HasKey("SteamId");
                    b.ToTable("player_preferences", "map_rotation", t =>
                        {
                            t.HasCheckConstraint("ck_player_preferences_orientation", "orientation IN ('horizontal', 'vertical')");
                            t.HasCheckConstraint("ck_player_preferences_hud_scale", "hud_scale IN (80, 100, 120)");
                            t.HasCheckConstraint("ck_player_preferences_dock_side", "dock_side IN ('left', 'right')");
                            t.HasCheckConstraint("ck_player_preferences_animation", "animation IN ('none', 'fast', 'normal', 'slow')");
                        });
                });

            modelBuilder.Entity("MapRotation.Core.Database.RuntimeEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Checkpoint")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("checkpoint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("runtime_state", "map_rotation");
                });

            modelBuilder.Entity("MapRotation.Core.Database.VoteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CurrentMap")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("current_map");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<long?>("WinnerMapId")
                        .HasColumnType("bigint")
                        .HasColumnName("winner_map_id");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.ToTable("vote_sessions", "map_rotation");
                });

            modelBuilder.Entity("MapRotation.Core.Database.VoteOptionEntity", b =>
                {
                    b.Property<Guid>("VoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("vote_id");

                    b.Property<long>("MapId")
                        .HasColumnType("bigint")
                        .HasColumnName("map_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("MapName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("map_name");

                    b.Property<int>("Votes")
                        .HasColumnType("integer")
                        .HasColumnName("votes");

                    b.HasKey("VoteId", "MapId");

                    b.ToTable("vote_options", "map_rotation");
                });

            modelBuilder.Entity("MapRotation.Core.Domain.RotationMap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("AllowAutoRotation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("allow_auto_rotation");

                    b.Property<bool>("AllowNomination")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("allow_nomination");

                    b.Property<bool>("AllowVote")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("allow_vote");

                    b.Property<int?>("CooldownMaps")
                        .HasColumnType("integer")
                        .HasColumnName("cooldown_maps");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name");

                    b.Property<string>("DisplayNameKey").HasMaxLength(191)
                        .HasColumnType("character varying(191)").HasColumnName("display_name_key");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<string>("HudImagePath")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("hud_image_path");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<string>("MapName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("map_name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<double>("Weight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(1.0)
                        .HasColumnName("weight");

                    b.Property<long?>("WorkshopId")
                        .HasColumnType("bigint")
                        .HasColumnName("workshop_id");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("MapName")
                        .IsUnique();

                    b.ToTable("maps", "map_rotation");
                });

            modelBuilder.Entity("MapRotation.Core.Domain.RotationSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<bool>("AllowSameMap")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_same_map");

                    b.Property<long>("ConfigurationVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("configuration_version");

                    b.Property<bool>("ExcludeBots")
                        .HasColumnType("boolean")
                        .HasColumnName("exclude_bots");

                    b.Property<long?>("FallbackMapId")
                        .HasColumnType("bigint")
                        .HasColumnName("fallback_map_id");

                    b.Property<int>("FinalRoundTimeoutSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("final_round_timeout_seconds");

                    b.Property<string>("HudSettings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("hud_settings");

                    b.Property<int>("MenuItemsPerPage")
                        .HasColumnType("integer")
                        .HasColumnName("menu_items_per_page");

                    b.Property<bool>("IncludeSpectators")
                        .HasColumnType("boolean")
                        .HasColumnName("include_spectators");

                    b.Property<int>("MapDurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("map_duration_seconds");

                    b.Property<int>("NominationSlots")
                        .HasColumnType("integer")
                        .HasColumnName("nomination_slots");

                    b.Property<bool>("NominationsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("nominations_enabled");

                    b.Property<int>("RecentMapsExcluded")
                        .HasColumnType("integer")
                        .HasColumnName("recent_maps_excluded");

                    b.Property<int>("RefreshIntervalSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("refresh_interval_seconds");

                    b.Property<int>("RtvChangeDelaySeconds")
                        .HasColumnType("integer")
                        .HasColumnName("rtv_change_delay_seconds");

                    b.Property<string>("RtvChangeMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rtv_change_mode");

                    b.Property<int>("RtvDelaySeconds")
                        .HasColumnType("integer")
                        .HasColumnName("rtv_delay_seconds");

                    b.Property<bool>("RtvEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("rtv_enabled");

                    b.Property<int>("RtvMinPlayers")
                        .HasColumnType("integer")
                        .HasColumnName("rtv_min_players");

                    b.Property<int>("RtvMinVotes")
                        .HasColumnType("integer")
                        .HasColumnName("rtv_min_votes");

                    b.Property<double>("RtvRatio")
                        .HasColumnType("double precision")
                        .HasColumnName("rtv_ratio");

                    b.Property<int>("ScheduledVoteBeforeSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("scheduled_vote_before_seconds");

                    b.Property<bool>("ScheduledVoteEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("scheduled_vote_enabled");

                    b.Property<int>("VoteDurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("vote_duration_seconds");

                    b.Property<int>("VoteOptionsCount")
                        .HasColumnType("integer")
                        .HasColumnName("vote_options_count");

                    b.HasKey("Id");

                    b.ToTable("settings", "map_rotation");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllowSameMap = false,
                            ConfigurationVersion = 1L,
                            ExcludeBots = true,
                            FinalRoundTimeoutSeconds = 600,
                            HudSettings = "{}",
                            MenuItemsPerPage = 12,
                            IncludeSpectators = true,
                            MapDurationSeconds = 2700,
                            NominationSlots = 3,
                            NominationsEnabled = true,
                            RecentMapsExcluded = 3,
                            RefreshIntervalSeconds = 15,
                            RtvChangeDelaySeconds = 0,
                            RtvChangeMode = "end_of_round",
                            RtvDelaySeconds = 300,
                            RtvEnabled = true,
                            RtvMinPlayers = 4,
                            RtvMinVotes = 3,
                            RtvRatio = 0.59999999999999998,
                            ScheduledVoteBeforeSeconds = 300,
                            ScheduledVoteEnabled = true,
                            VoteDurationSeconds = 20,
                            VoteOptionsCount = 6
                        });
                });

            modelBuilder.Entity("MapRotation.Core.Database.VoteOptionEntity", b =>
                {
                    b.HasOne("MapRotation.Core.Database.VoteEntity", null)
                        .WithMany()
                        .HasForeignKey("VoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
