// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Statistics.Core.Database;

#nullable disable

namespace Statistics.Core.Database.Migrations
{
    [DbContext(typeof(StatisticsDbContext))]
    [Migration("20260823180000_RefactorStatisticsSchema")]
    partial class RefactorStatisticsSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("statistics")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Statistics.Core.Database.Entities.PlayerEntity", b =>
                {
                    b.Property<long>("SteamId")
                        .ValueGeneratedNever()
                        .HasColumnType("bigint")
                        .HasColumnName("steam_id");

                    b.Property<DateTime>("FirstSeenAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("LastKnownName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("last_known_name");

                    b.HasKey("SteamId");

                    b.ToTable("players", "statistics");
                });

            modelBuilder.Entity("Statistics.Core.Database.Entities.PlayerStatisticsEntity", b =>
                {
                    b.Property<long>("SteamId")
                        .ValueGeneratedNever()
                        .HasColumnType("bigint")
                        .HasColumnName("steam_id");

                    b.Property<long>("BestInfectionStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("best_infection_streak")
                        .HasDefaultValue(0L);

                    b.Property<long>("BestKillStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("best_kill_streak")
                        .HasDefaultValue(0L);

                    b.Property<long>("Deaths")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("deaths")
                        .HasDefaultValue(0L);

                    b.Property<long>("HumanWins")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("human_wins")
                        .HasDefaultValue(0L);

                    b.Property<long>("InfectionsMade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("infections_made")
                        .HasDefaultValue(0L);

                    b.Property<long>("PlayTimeSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("play_time_seconds")
                        .HasDefaultValue(0L);

                    b.Property<long>("Points")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("points")
                        .HasDefaultValue(0L);

                    b.Property<long>("TimesInfected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("times_infected")
                        .HasDefaultValue(0L);

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("ZombiesKilled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("zombies_killed")
                        .HasDefaultValue(0L);

                    b.Property<long>("ZombieWins")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("zombie_wins")
                        .HasDefaultValue(0L);

                    b.HasKey("SteamId");

                    b.ToTable("player_statistics", "statistics", t =>
                        {
                            t.HasCheckConstraint("CK_player_statistics_points_non_negative", "points >= 0");
                        });
                });

            modelBuilder.Entity("Statistics.Core.Database.Entities.PlayerStatisticsEntity", b =>
                {
                    b.HasOne("Statistics.Core.Database.Entities.PlayerEntity", "Player")
                        .WithOne("Statistics")
                        .HasForeignKey("Statistics.Core.Database.Entities.PlayerStatisticsEntity", "SteamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Statistics.Core.Database.Entities.PlayerEntity", b =>
                {
                    b.Navigation("Statistics");
                });
#pragma warning restore 612, 618
        }
    }
}
