// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Statistics.Core.Database;

#nullable disable

namespace Statistics.Core.Database.Migrations
{
    [DbContext(typeof(StatisticsDbContext))]
    partial class StatisticsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("statistics")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Statistics.Core.Database.Entities.PlayerEntity", b =>
                {
                    b.Property<long>("SteamId")
                        .ValueGeneratedNever()
                        .HasColumnType("bigint")
                        .HasColumnName("steam_id");

                    b.Property<DateTime>("FirstSeenAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("LastKnownName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("last_known_name");

                    b.HasKey("SteamId");

                    b.ToTable("players", "statistics");
                });

            modelBuilder.Entity("Statistics.Core.Database.Entities.PlayerStatisticsEntity", b =>
                {
                    b.Property<long>("BestInfectionStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("best_infection_streak")
                        .HasDefaultValue(0L);

                    b.Property<long>("BestKillStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("best_kill_streak")
                        .HasDefaultValue(0L);

                    b.Property<long>("DamageToHumans")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("damage_to_humans")
                        .HasDefaultValue(0L);

                    b.Property<long>("DamageToZombies")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("damage_to_zombies")
                        .HasDefaultValue(0L);

                    b.Property<long>("DeathsAsHuman")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("deaths_as_human")
                        .HasDefaultValue(0L);

                    b.Property<long>("DeathsAsZombie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("deaths_as_zombie")
                        .HasDefaultValue(0L);

                    b.Property<long>("FirstZombieRounds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("first_zombie_rounds")
                        .HasDefaultValue(0L);

                    b.Property<long>("HeadshotZombieKills")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("headshot_zombie_kills")
                        .HasDefaultValue(0L);

                    b.Property<long>("HumanWins")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("human_wins")
                        .HasDefaultValue(0L);

                    b.Property<long>("InfectionsMade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("infections_made")
                        .HasDefaultValue(0L);

                    b.Property<long>("LastHumanRounds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("last_human_rounds")
                        .HasDefaultValue(0L);

                    b.Property<long>("LastHumanSurvivals")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("last_human_survivals")
                        .HasDefaultValue(0L);

                    b.Property<long>("PlayTimeSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("play_time_seconds")
                        .HasDefaultValue(0L);

                    b.Property<long>("RoundsAsHuman")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("rounds_as_human")
                        .HasDefaultValue(0L);

                    b.Property<long>("RoundsAsZombie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("rounds_as_zombie")
                        .HasDefaultValue(0L);

                    b.Property<long>("RoundsPlayed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("rounds_played")
                        .HasDefaultValue(0L);

                    b.Property<long>("SessionsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sessions_count")
                        .HasDefaultValue(0L);

                    b.Property<long>("SurvivedRounds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("survived_rounds")
                        .HasDefaultValue(0L);

                    b.Property<long>("TimesInfected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("times_infected")
                        .HasDefaultValue(0L);

                    b.Property<long>("ZombiesKilled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("zombies_killed")
                        .HasDefaultValue(0L);

                    b.Property<long>("ZombieWins")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("zombie_wins")
                        .HasDefaultValue(0L);

                    b.Property<long>("SteamId")
                        .ValueGeneratedNever()
                        .HasColumnType("bigint")
                        .HasColumnName("steam_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("SteamId");

                    b.ToTable("player_statistics", "statistics");
                });

            modelBuilder.Entity("Statistics.Core.Database.Entities.PlayerStatisticsEntity", b =>
                {
                    b.HasOne("Statistics.Core.Database.Entities.PlayerEntity", "Player")
                        .WithOne("Statistics")
                        .HasForeignKey("Statistics.Core.Database.Entities.PlayerStatisticsEntity", "SteamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Statistics.Core.Database.Entities.PlayerEntity", b =>
                {
                    b.Navigation("Statistics");
                });
#pragma warning restore 612, 618
        }
    }
}
