// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZombiePlague.Core.Database;

#nullable disable

namespace ZombiePlague.Core.Database.Migrations;

[DbContext(typeof(ZombiePlagueDbContext))]
partial class ZombiePlagueDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("zombie_plague")
            .HasAnnotation("ProductVersion", "9.0.3")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("ZombiePlague.Core.Database.Entities.PlayerEntity", builder =>
        {
            builder.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer")
                .HasColumnName("id");

            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(builder.Property<int>("Id"));

            builder.Property<string>("HumanClassId")
                .IsRequired()
                .ValueGeneratedOnAdd()
                .HasMaxLength(64)
                .HasColumnType("character varying(64)")
                .HasDefaultValue("human_mercenary")
                .HasColumnName("human_class");

            builder.Property<long>("SteamId")
                .HasColumnType("bigint")
                .HasColumnName("steam_id");

            builder.Property<DateTime>("UpdatedAtUtc")
                .ValueGeneratedOnAdd()
                .HasColumnType("timestamp with time zone")
                .HasColumnName("updated_at")
                .HasDefaultValueSql("CURRENT_TIMESTAMP");

            builder.Property<string>("ZombieClassId")
                .IsRequired()
                .ValueGeneratedOnAdd()
                .HasMaxLength(64)
                .HasColumnType("character varying(64)")
                .HasDefaultValue("zombie_cleric")
                .HasColumnName("zombie_class");

            builder.HasKey("Id");

            builder.HasIndex("SteamId")
                .IsUnique()
                .HasDatabaseName("ux_players_steam_id");

            builder.ToTable("players", "zombie_plague");
        });
#pragma warning restore 612, 618
    }
}
