<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <PublishDir>$(OutputPath)publish/ZombiePlague.Core</PublishDir>
        <AssemblyName>ZombiePlague.Core</AssemblyName>
        <PluginVersion>0.1.0</PluginVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" ExcludeAssets="runtime" PrivateAssets="all"/>
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.0" ExcludeAssets="runtime" PrivateAssets="all"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.0" ExcludeAssets="runtime" PrivateAssets="all"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.0" ExcludeAssets="runtime" PrivateAssets="all"/>
        <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.0" ExcludeAssets="runtime" PrivateAssets="all"/>
        <PackageReference Include="SwiftlyS2.CS2" Version="1.4.0-beta.37" ExcludeAssets="runtime" PrivateAssets="all">
            <IncludeAssets>compile; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <Content Include="resources/gamedata/**/*;resources/templates/**/*;resources/translations/**/*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="examples\**\*.cs"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Common.Effects\Common.Effects.csproj" />
        <ProjectReference Include="..\Menu.Api\Menu.Api.csproj" />
        <ProjectReference Include="..\ZombiePlague.Api\ZombiePlague.Api.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="resources\exports\"/>
        <Folder Include="src\Data\Rounds\Exceptions\" />
    </ItemGroup>

    <Target Name="CreateZip" AfterTargets="Publish">
        <ItemGroup>
            <PublishFiles Include="$(PublishDir)**\*.*"/>
        </ItemGroup>

        <ZipDirectory SourceDirectory="$(PublishDir)../" DestinationFile="$(OutputPath)../$(AssemblyName).zip" Overwrite="true"/>
    </Target>

    <ItemGroup>
        <VersionFileLines Include="namespace $(AssemblyName).Generated {&#x0D;&#x0A;%09internal static class BuildInfo {&#x0D;&#x0A;%09%09internal const string Version = %22$(PluginVersion)%22%3B&#x0D;&#x0A;%09}&#x0D;&#x0A;}"/>
    </ItemGroup>

    <Target Name="GenerateVersionFile" BeforeTargets="CoreCompile">
        <WriteLinesToFile
                File="$(IntermediateOutputPath)BuildInfo.cs"
                Lines="@(VersionFileLines)"
                Overwrite="true" />

        <ItemGroup>
            <Compile Include="$(IntermediateOutputPath)BuildInfo.cs" />
        </ItemGroup>
    </Target>

</Project> 
