<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <GenerateAssemblyInfo>true</GenerateAssemblyInfo>

        <PublishDir>$(OutputPath)publish/CustomKnife</PublishDir>

        <PackageId>CustomKnife.Core</PackageId>
        <RootNamespace>CustomKnife</RootNamespace>

        <Configurations>Debug;Release;Migrations</Configurations>
    </PropertyGroup>

    <!-- EF Core -->
    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.3" />

        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.3">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>

        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.3" />

    </ItemGroup>

    <!-- Обычная сборка плагина -->
    <ItemGroup Condition="'$(Configuration)' != 'Migrations'">

        <PackageReference Include="Microsoft.Extensions.DependencyInjection"
                          Version="10.0.0"
                          ExcludeAssets="runtime"
                          PrivateAssets="all" />

        <PackageReference Include="Microsoft.Extensions.Configuration"
                          Version="10.0.0"
                          ExcludeAssets="runtime"
                          PrivateAssets="all" />

        <PackageReference Include="Microsoft.Extensions.Configuration.Json"
                          Version="10.0.0"
                          ExcludeAssets="runtime"
                          PrivateAssets="all" />

        <PackageReference Include="Microsoft.Extensions.Configuration.Binder"
                          Version="10.0.0"
                          ExcludeAssets="runtime"
                          PrivateAssets="all" />

        <PackageReference Include="Microsoft.Extensions.Logging"
                          Version="10.0.0"
                          ExcludeAssets="runtime"
                          PrivateAssets="all" />

        <PackageReference Include="SwiftlyS2.CS2" Version="1.4.6-beta.8" ExcludeAssets="runtime" PrivateAssets="all">
            <IncludeAssets>compile; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>

    </ItemGroup>

    <!-- Только для dotnet ef -->
    <ItemGroup Condition="'$(Configuration)' == 'Migrations'">

        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" PrivateAssets="all" />

        <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.0" PrivateAssets="all" />

        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.0" PrivateAssets="all" />

        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.0" PrivateAssets="all" />

        <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.0" PrivateAssets="all" />

        <PackageReference Include="SwiftlyS2.CS2" Version="1.4.6-beta.8" PrivateAssets="all">
          <IncludeAssets>compile; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>

    </ItemGroup>

    <ItemGroup>
        <Content Include="resources/gamedata/**/*;resources/templates/**/*;resources/translations/**/*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="examples\**\*.cs"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Admin.Api\Admin.Api.csproj" />
        <ProjectReference Include="..\Common.Database\Common.Database.csproj">
            <Private>true</Private>
        </ProjectReference>
        <ProjectReference Include="..\Common.Di\Common.Di.csproj" />
        <ProjectReference Include="..\Localization.Api\Localization.Api.csproj" />
        <ProjectReference Include="..\Menu.Api\Menu.Api.csproj" />
        <ProjectReference Include="..\ZombiePlague.Api\ZombiePlague.Api.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="src\Database\Migrations\" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="CustomKnife.Core.Tests" />
    </ItemGroup>

</Project>
